MahoganyTown_House_EventObjects::
	object_event 1, EVENT_OBJ_GFX_BLACK_BELT, 0, 2, 3, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 0, 0, VerdanturfTown_House_EventScript_20335F, 0
	object_event 2, EVENT_OBJ_GFX_TEACHER, PAL_NPC_BLUE, 6, 5, 3, MOVEMENT_TYPE_WANDER_UP_AND_DOWN, 0, 1, 0, 0, VerdanturfTown_House_EventScript_203368, 0

MahoganyTown_House_MapWarps::
	warp_def 2, 7, 0, 1, MAP_MAHOGANY_TOWN
	warp_def 3, 7, 0, 1, MAP_MAHOGANY_TOWN

MahoganyTown_House_MapEvents::
	map_events MahoganyTown_House_EventObjects, MahoganyTown_House_MapWarps, 0x0, 0x0
