WhirlIslands_Cave::
	.4byte WhirlIslands_Cave_Layout
	.4byte WhirlIslands_Cave_MapEvents
	.4byte WhirlIslands_Cave_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte 2697
	.byte MAPSEC_WHIRL_ISLANDS
	.byte FALSE
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_UNDERGROUND
	.2byte PAL_DUNGEON_DARK
	map_header_flags allow_bike=1, allow_escape_rope=1, allow_run=0, show_map_name=TRUE
	.byte MAP_BATTLE_SCENE_NORMAL
