SeafloorCavern_Room7_MapWarps::
	warp_def 10, 3, 3, 3, MAP_SEAFLOOR_CAVERN_ROOM2
	warp_def 16, 7, 3, 1, MAP_SEAFLOOR_CAVERN_ROOM3
	warp_def 2, 5, 3, 0, MAP_SEAFLOOR_CAVERN_ROOM7
	warp_def 2, 11, 3, 0, MAP_SEAFLOOR_CAVERN_ROOM7
	warp_def 6, 9, 3, 0, MAP_SEAFLOOR_CAVERN_ROOM7
	warp_def 14, 15, 3, 0, MAP_SEAFLOOR_CAVERN_ROOM7

SeafloorCavern_Room7_MapEvents::
	map_events 0x0, SeafloorCavern_Room7_MapWarps, 0x0, 0x0
