GoldenrodCity_DepartmentStoreElevator_MapWarps::
	warp_def 1, 3, 3, 127, MAP_NONE
	warp_def 2, 3, 3, 127, MAP_NONE

GoldenrodCity_DepartmentStoreElevator_MapBGEvents::
	bg_event 3, 0, 3, BG_EVENT_PLAYER_FACING_ANY, LilycoveCity_DepartmentStoreElevator_EventScript_220624

GoldenrodCity_DepartmentStoreElevator_MapEvents::
	map_events 0x0, GoldenrodCity_DepartmentStoreElevator_MapWarps, 0x0, GoldenrodCity_DepartmentStoreElevator_MapBGEvents
