DragonsDen_Entrance::
	.4byte DragonsDen_Entrance_Layout
	.4byte DragonsDen_Entrance_MapEvents
	.4byte DragonsDen_Entrance_MapScripts
	.4byte 0x0
	.2byte MUS_DEEPDEEP
	.2byte 146
	.byte MAPSEC_DRAGONS_DEN
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_UNDERGROUND
	.2byte PAL_DUNGEON_NITE
	map_header_flags allow_bike=1, allow_escape_rope=1, allow_run=0, show_map_name=1
	.byte MAP_BATTLE_SCENE_NORMAL
