WhirlIslands_LugiasChamber:
	.4byte WhirlIslands_LugiasChamber_Layout
	.4byte WhirlIslands_LugiasChamber_MapEvents
	.4byte WhirlIslands_LugiasChamber_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_WHIRL_ISLANDS_LUGIAS_CHAMBER
	.byte MAPSEC_WHIRL_ISLANDS
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_UNDERGROUND
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=1, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

