BattlePyramidSquare03_EventObjects:
	object_event 1, EVENT_OBJ_GFX_YOUNGSTER, 0, 2, 1, 4, MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT, 1, 1, 1, 5, BattlePyramid_TrainerBattle, 0
	object_event 2, EVENT_OBJ_GFX_ZLITTLE_BOY, 0, 6, 1, 4, MOVEMENT_TYPE_FACE_DOWN_AND_LEFT, 1, 1, 1, 4, BattlePyramid_TrainerBattle, 0
	object_event 3, EVENT_OBJ_GFX_ZFISHERMAN, 0, 6, 4, 4, MOVEMENT_TYPE_FACE_UP_AND_LEFT, 1, 1, 1, 3, BattlePyramid_TrainerBattle, 0
	object_event 4, EVENT_OBJ_GFX_COOLTRAINER_M, 0, 3, 4, 4, MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT, 1, 1, 1, 4, BattlePyramid_TrainerBattle, 0
	object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 4, 2, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattlePyramid_FindItemBall, 0
	object_event 6, EVENT_OBJ_GFX_ITEM_BALL, 0, 0, 3, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattlePyramid_FindItemBall, 0
	object_event 7, EVENT_OBJ_GFX_ITEM_BALL, 0, 2, 7, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattlePyramid_FindItemBall, 0

BattlePyramidSquare03_MapEvents::
	map_events BattlePyramidSquare03_EventObjects, 0x0, 0x0, 0x0

