BlackthornCity_House2_EventObjects::
	object_event 1, EVENT_OBJ_GFX_LASS, PAL_NPC_GREEN, 2, 3, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, FortreeCity_House2_EventScript_2177CB, 0

BlackthornCity_House2_MapWarps::
	warp_def 2, 7, 0, 2, MAP_BLACKTHORN_CITY
	warp_def 3, 7, 0, 2, MAP_BLACKTHORN_CITY

BlackthornCity_House2_MapEvents::
	map_events BlackthornCity_House2_EventObjects, BlackthornCity_House2_MapWarps, 0x0, 0x0
