EcruteakCity_DanceTheater::
	.4byte EcruteakCity_DanceTheater_Layout
	.4byte EcruteakCity_DanceTheater_MapEvents
	.4byte EcruteakCity_DanceTheater_MapScripts
	.4byte 0x0
	.2byte MUS_GOTOWN
	.2byte 269
	.byte MAPSEC_ECRUTEAK_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte PAL_INDOOR
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
