MahoganyTown_PokemonCenter_2F::
	.4byte PokemonCenter_2F_Layout
	.4byte MahoganyTown_PokemonCenter_2F_MapEvents
	.4byte MahoganyTown_PokemonCenter_2F_MapScripts
	.4byte 0x0
	.2byte MUS_POKECEN
	.2byte 62
	.byte MAPSEC_MAHOGANY_TOWN
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte PAL_INDOOR
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
