#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define EVENT_OBJ_GFX_GOLD_NORMAL                  0
#define EVENT_OBJ_GFX_GOLD_MACH_BIKE               1
#define EVENT_OBJ_GFX_ZBRENDAN_SURFING             2
#define EVENT_OBJ_GFX_ZBRENDAN_FIELD_MOVE          3
#define EVENT_OBJ_GFX_SURGE                        4
#define EVENT_OBJ_GFX_ZNINJA_BOY                   5
#define EVENT_OBJ_GFX_TWIN                         6
#define EVENT_OBJ_GFX_BLAINE                       7
#define EVENT_OBJ_GFX_ZGIRL_1                      8
#define EVENT_OBJ_GFX_ZBOY_2                       9
#define EVENT_OBJ_GFX_ZGIRL_2                     10
#define EVENT_OBJ_GFX_ZLITTLE_BOY                 11
#define EVENT_OBJ_GFX_ZLITTLE_GIRL                12
#define EVENT_OBJ_GFX_ZBOY_3                      13
#define EVENT_OBJ_GFX_ZGIRL_3                     14
#define EVENT_OBJ_GFX_ZRICH_BOY                   15
#define EVENT_OBJ_GFX_ZWOMAN_1                    16
#define EVENT_OBJ_GFX_FAT_MAN                     17
#define EVENT_OBJ_GFX_POKEFAN_F                   18
#define EVENT_OBJ_GFX_ZMAN_1                      19
#define EVENT_OBJ_GFX_ZWOMAN_2                    20
#define EVENT_OBJ_GFX_SAGE                        21
#define EVENT_OBJ_GFX_TEACHER                     22
#define EVENT_OBJ_GFX_GYM_GUIDE                   23
#define EVENT_OBJ_GFX_ZWOMAN_3                    24
#define EVENT_OBJ_GFX_POKEFAN_M                   25
#define EVENT_OBJ_GFX_ZWOMAN_4                    26
#define EVENT_OBJ_GFX_CAPTAIN                     27
#define EVENT_OBJ_GFX_RECEPTIONIST                28
#define EVENT_OBJ_GFX_OLD_MAN                     29
#define EVENT_OBJ_GFX_REDS_MOM                    30
#define EVENT_OBJ_GFX_ZCAMPER                     31
#define EVENT_OBJ_GFX_ZPICNICKER                  32
#define EVENT_OBJ_GFX_COOLTRAINER_M               33
#define EVENT_OBJ_GFX_COOLTRAINER_F               34
#define EVENT_OBJ_GFX_YOUNGSTER                   35
#define EVENT_OBJ_GFX_BUG_CATCHER                 36
#define EVENT_OBJ_GFX_ZPSYCHIC_M                  37
#define EVENT_OBJ_GFX_ZSCHOOL_KID_M               38
#define EVENT_OBJ_GFX_SUPER_NERD                  39
#define EVENT_OBJ_GFX_OLD_WOMAN                   40
#define EVENT_OBJ_GFX_ZRAYQUAZA_1                 41
#define EVENT_OBJ_GFX_SWIMMER_M                   42
#define EVENT_OBJ_GFX_SWIMMER_F                   43
#define EVENT_OBJ_GFX_BLACK_BELT                  44
#define EVENT_OBJ_GFX_BEAUTY                      45
#define EVENT_OBJ_GFX_SCIENTIST                   46
#define EVENT_OBJ_GFX_LASS                        47
#define EVENT_OBJ_GFX_GENTLEMAN                   48
#define EVENT_OBJ_GFX_SAILOR                      49
#define EVENT_OBJ_GFX_ZFISHERMAN                  50
#define EVENT_OBJ_GFX_ZRUNNING_TRIATHLETE_M       51
#define EVENT_OBJ_GFX_ZRUNNING_TRIATHLETE_F       52
#define EVENT_OBJ_GFX_ZTUBER_F                    53
#define EVENT_OBJ_GFX_ZTUBER_M                    54
#define EVENT_OBJ_GFX_ZHIKER                      55
#define EVENT_OBJ_GFX_BIKER                       56
#define EVENT_OBJ_GFX_ZCYCLING_TRIATHLETE_F       57
#define EVENT_OBJ_GFX_NURSE                       58
#define EVENT_OBJ_GFX_ITEM_BALL                   59
#define EVENT_OBJ_GFX_ZBERRY_TREE_HOENN           60
#define EVENT_OBJ_GFX_ZBERRY_TREE_EARLY_STAGES    61
#define EVENT_OBJ_GFX_ZBERRY_TREE_LATE_STAGES     62
#define EVENT_OBJ_GFX_ZBRENDAN_ACRO_BIKE          63
#define EVENT_OBJ_GFX_PROF_ELM                    64
#define EVENT_OBJ_GFX_ZMAN_4                      65
#define EVENT_OBJ_GFX_ZMAN_5                      66
#define EVENT_OBJ_GFX_ZREPORTER_M                 67
#define EVENT_OBJ_GFX_ZREPORTER_F                 68
#define EVENT_OBJ_GFX_ZBARD                       69
#define EVENT_OBJ_GFX_ZANABEL                     70
#define EVENT_OBJ_GFX_ZTUCKER                     71
#define EVENT_OBJ_GFX_ZGRETA                      72
#define EVENT_OBJ_GFX_ZSPENSER                    73
#define EVENT_OBJ_GFX_ZNOLAND                     74
#define EVENT_OBJ_GFX_ZLUCY                       75
#define EVENT_OBJ_GFX_ZUNUSED_NATU_DOLL           76
#define EVENT_OBJ_GFX_ZUNUSED_MAGNEMITE_DOLL      77
#define EVENT_OBJ_GFX_ZUNUSED_SQUIRTLE_DOLL       78
#define EVENT_OBJ_GFX_ZUNUSED_WOOPER_DOLL         79
#define EVENT_OBJ_GFX_ZUNUSED_PIKACHU_DOLL        80
#define EVENT_OBJ_GFX_ZUNUSED_PORYGON2_DOLL       81
#define EVENT_OBJ_GFX_CUTTABLE_TREE               82
#define EVENT_OBJ_GFX_MART_EMPLOYEE               83
#define EVENT_OBJ_GFX_KIMONO_GIRL                 84
#define EVENT_OBJ_GFX_TEALA                       85
#define EVENT_OBJ_GFX_BREAKABLE_ROCK              86
#define EVENT_OBJ_GFX_PUSHABLE_BOULDER            87
#define EVENT_OBJ_GFX_SABRINA                     88
#define EVENT_OBJ_GFX_KRIS_NORMAL                 89
#define EVENT_OBJ_GFX_KRIS_MACH_BIKE              90
#define EVENT_OBJ_GFX_ZMAY_ACRO_BIKE              91
#define EVENT_OBJ_GFX_ZMAY_SURFING                92
#define EVENT_OBJ_GFX_ZMAY_FIELD_MOVE             93
#define EVENT_OBJ_GFX_SNES                        94
#define EVENT_OBJ_GFX_GOLD_TROPHY                 95
#define EVENT_OBJ_GFX_SILVER_TROPHY               96
#define EVENT_OBJ_GFX_PAPER                       97
#define EVENT_OBJ_GFX_RHYDON                      98
#define EVENT_OBJ_GFX_ERIKA                       99
#define EVENT_OBJ_GFX_ZRIVAL_BRENDAN_NORMAL      100
#define EVENT_OBJ_GFX_ZRIVAL_BRENDAN_MACH_BIKE   101
#define EVENT_OBJ_GFX_ZRIVAL_BRENDAN_ACRO_BIKE   102
#define EVENT_OBJ_GFX_ZRIVAL_BRENDAN_SURFING     103
#define EVENT_OBJ_GFX_ZRIVAL_BRENDAN_FIELD_MOVE  104
#define EVENT_OBJ_GFX_ZRIVAL_MAY_NORMAL          105
#define EVENT_OBJ_GFX_ZRIVAL_MAY_MACH_BIKE       106
#define EVENT_OBJ_GFX_ZRIVAL_MAY_ACRO_BIKE       107
#define EVENT_OBJ_GFX_ZRIVAL_MAY_SURFING         108
#define EVENT_OBJ_GFX_ZRIVAL_MAY_FIELD_MOVE      109
#define EVENT_OBJ_GFX_ZCAMERAMAN                 110
#define EVENT_OBJ_GFX_ZBRENDAN_UNDERWATER        111
#define EVENT_OBJ_GFX_ZMAY_UNDERWATER            112
#define EVENT_OBJ_GFX_BOOK                       113
#define EVENT_OBJ_GFX_ZCABLE_CAR                 114
#define EVENT_OBJ_GFX_PROF_OAK                   115
#define EVENT_OBJ_GFX_FISHING_GURU               116
#define EVENT_OBJ_GFX_BILL                       117
#define EVENT_OBJ_GFX_KURT                       118
#define EVENT_OBJ_GFX_ROCKET_GRUNT_M             119
#define EVENT_OBJ_GFX_ROCKET_GRUNT_F             120
#define EVENT_OBJ_GFX_WILL                       121
#define EVENT_OBJ_GFX_KAREN                      122
#define EVENT_OBJ_GFX_BRUNO                      123
#define EVENT_OBJ_GFX_KOGA                       124
#define EVENT_OBJ_GFX_FALKNER                    125
#define EVENT_OBJ_GFX_BUGSY                      126
#define EVENT_OBJ_GFX_WHITNEY                    127
#define EVENT_OBJ_GFX_MORTY                      128
#define EVENT_OBJ_GFX_CHUCK                      129
#define EVENT_OBJ_GFX_JASMINE                    130
#define EVENT_OBJ_GFX_PRYCE                      131
#define EVENT_OBJ_GFX_CLAIR                      132
#define EVENT_OBJ_GFX_BROCK                      133
#define EVENT_OBJ_GFX_LANCE                      134
#define EVENT_OBJ_GFX_JANINE                     135
#define EVENT_OBJ_GFX_OFFICER                    136
#define EVENT_OBJ_GFX_BRENDAN_FISHING            137
#define EVENT_OBJ_GFX_MAY_FISHING                138
#define EVENT_OBJ_GFX_GUITARIST                  139
#define EVENT_OBJ_GFX_ZSS_TIDAL                  140
#define EVENT_OBJ_GFX_N64                        141
#define EVENT_OBJ_GFX_ZPICHU_DOLL                142
#define EVENT_OBJ_GFX_ZPIKACHU_DOLL              143
#define EVENT_OBJ_GFX_ZMARILL_DOLL               144
#define EVENT_OBJ_GFX_ZTOGEPI_DOLL               145
#define EVENT_OBJ_GFX_ZCYNDAQUIL_DOLL            146
#define EVENT_OBJ_GFX_ZCHIKORITA_DOLL            147
#define EVENT_OBJ_GFX_ZTOTODILE_DOLL             148
#define EVENT_OBJ_GFX_ZJIGGLYPUFF_DOLL           149
#define EVENT_OBJ_GFX_ZMEOWTH_DOLL               150
#define EVENT_OBJ_GFX_ZCLEFAIRY_DOLL             151
#define EVENT_OBJ_GFX_ZDITTO_DOLL                152
#define EVENT_OBJ_GFX_ZSMOOCHUM_DOLL             153
#define EVENT_OBJ_GFX_ZTREECKO_DOLL              154
#define EVENT_OBJ_GFX_ZTORCHIC_DOLL              155
#define EVENT_OBJ_GFX_ZMUDKIP_DOLL               156
#define EVENT_OBJ_GFX_ZDUSKULL_DOLL              157
#define EVENT_OBJ_GFX_ZWYNAUT_DOLL               158
#define EVENT_OBJ_GFX_ZBALTOY_DOLL               159
#define EVENT_OBJ_GFX_ZKECLEON_DOLL              160
#define EVENT_OBJ_GFX_ZAZURILL_DOLL              161
#define EVENT_OBJ_GFX_ZSKITTY_DOLL               162
#define EVENT_OBJ_GFX_ZSWABLU_DOLL               163
#define EVENT_OBJ_GFX_ZGULPIN_DOLL               164
#define EVENT_OBJ_GFX_ZLOTAD_DOLL                165
#define EVENT_OBJ_GFX_ZSEEDOT_DOLL               166
#define EVENT_OBJ_GFX_ZPIKA_CUSHION              167
#define EVENT_OBJ_GFX_ZROUND_CUSHION             168
#define EVENT_OBJ_GFX_ZKISS_CUSHION              169
#define EVENT_OBJ_GFX_ZZIGZAG_CUSHION            170
#define EVENT_OBJ_GFX_ZSPIN_CUSHION              171
#define EVENT_OBJ_GFX_ZDIAMOND_CUSHION           172
#define EVENT_OBJ_GFX_ZBALL_CUSHION              173
#define EVENT_OBJ_GFX_ZGRASS_CUSHION             174
#define EVENT_OBJ_GFX_ZFIRE_CUSHION              175
#define EVENT_OBJ_GFX_ZWATER_CUSHION             176
#define EVENT_OBJ_GFX_BIG_SNORLAX_DOLL           177
#define EVENT_OBJ_GFX_ZBIG_RHYDON_DOLL           178
#define EVENT_OBJ_GFX_BIG_LAPRAS_DOLL            179
#define EVENT_OBJ_GFX_ZBIG_VENUSAUR_DOLL         180
#define EVENT_OBJ_GFX_ZBIG_CHARIZARD_DOLL        181
#define EVENT_OBJ_GFX_ZBIG_BLASTOISE_DOLL        182
#define EVENT_OBJ_GFX_ZBIG_WAILMER_DOLL          183
#define EVENT_OBJ_GFX_ZBIG_REGIROCK_DOLL         184
#define EVENT_OBJ_GFX_ZBIG_REGICE_DOLL           185
#define EVENT_OBJ_GFX_ZBIG_REGISTEEL_DOLL        186
#define EVENT_OBJ_GFX_ZLATIAS                    187
#define EVENT_OBJ_GFX_ZLATIOS                    188
#define EVENT_OBJ_GFX_GAMEBOY_KID                189
#define EVENT_OBJ_GFX_ELDER                      190
#define EVENT_OBJ_GFX_ZBRENDAN_WATERING          191
#define EVENT_OBJ_GFX_ZMAY_WATERING              192
#define EVENT_OBJ_GFX_ZBRENDAN_DECORATING        193
#define EVENT_OBJ_GFX_ZMAY_DECORATING            194
#define EVENT_OBJ_GFX_DAISY                      195
#define EVENT_OBJ_GFX_RIVAL                      196
#define EVENT_OBJ_GFX_ZKYOGRE_1                  197
#define EVENT_OBJ_GFX_ZGROUDON_1                 198
#define EVENT_OBJ_GFX_BERRY_TREE                 199
#define EVENT_OBJ_GFX_BIG_ONIX_DOLL              200
#define EVENT_OBJ_GFX_VIRTUAL_BOY                201
#define EVENT_OBJ_GFX_ZREGISTEEL                 202
#define EVENT_OBJ_GFX_SLOWPOKE                   203
#define EVENT_OBJ_GFX_SUICUNE                    204
#define EVENT_OBJ_GFX_ZKYOGRE_2                  205
#define EVENT_OBJ_GFX_ZGROUDON_2                 206
#define EVENT_OBJ_GFX_ZRAYQUAZA_2                207
#define EVENT_OBJ_GFX_ZZIGZAGOON_2               208
#define EVENT_OBJ_GFX_RAIKOU                     209
#define EVENT_OBJ_GFX_SURFING_LAPRAS             210
#define EVENT_OBJ_GFX_BIRD                       211
#define EVENT_OBJ_GFX_CAL                        212
#define EVENT_OBJ_GFX_MISTY                      213
#define EVENT_OBJ_GFX_ENTEI                      214
#define EVENT_OBJ_GFX_MOM                        215
#define EVENT_OBJ_GFX_LINK_BRENDAN               216
#define EVENT_OBJ_GFX_LINK_MAY                   217
#define EVENT_OBJ_GFX_BLUE                       218
#define EVENT_OBJ_GFX_PHARMACIST                 219
#define EVENT_OBJ_GFX_SURFING_PIKACHU            220
#define EVENT_OBJ_GFX_ZKYOGRE_3                  221
#define EVENT_OBJ_GFX_ZGROUDON_3                 222
#define EVENT_OBJ_GFX_ZMYSTERY_GIFT_MAN          223
#define EVENT_OBJ_GFX_FAMICOM                    224
#define EVENT_OBJ_GFX_CLEFAIRY                   225
#define EVENT_OBJ_GFX_DRAGONITE                  226
#define EVENT_OBJ_GFX_ZUNION_ROOM_NURSE          227
#define EVENT_OBJ_GFX_SUDOWOODO                  228
#define EVENT_OBJ_GFX_ZMEW                       229
#define EVENT_OBJ_GFX_RED                        230
#define EVENT_OBJ_GFX_LEAF                       231
#define EVENT_OBJ_GFX_ZDEOXYS                    232
#define EVENT_OBJ_GFX_ZDEOXYS_TRIANGLE           233
#define EVENT_OBJ_GFX_ZBRANDON                   234
#define EVENT_OBJ_GFX_LINK_RS_BRENDAN            235
#define EVENT_OBJ_GFX_LINK_RS_MAY                236
#define EVENT_OBJ_GFX_ZLUGIA                     237
#define EVENT_OBJ_GFX_ZHOOH                      238
#define EVENT_OBJ_GFX_ZBARD_2                    239

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define EVENT_OBJ_GFX_VAR_0 240
#define EVENT_OBJ_GFX_VAR_1 241
#define EVENT_OBJ_GFX_VAR_2 242
#define EVENT_OBJ_GFX_VAR_3 243
#define EVENT_OBJ_GFX_VAR_4 244
#define EVENT_OBJ_GFX_VAR_5 245
#define EVENT_OBJ_GFX_VAR_6 246
#define EVENT_OBJ_GFX_VAR_7 247
#define EVENT_OBJ_GFX_VAR_8 248
#define EVENT_OBJ_GFX_VAR_9 249
#define EVENT_OBJ_GFX_VAR_A 250
#define EVENT_OBJ_GFX_VAR_B 251
#define EVENT_OBJ_GFX_VAR_C 252
#define EVENT_OBJ_GFX_VAR_D 253
#define EVENT_OBJ_GFX_VAR_E 254
#define EVENT_OBJ_GFX_VAR_F 255

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX EVENT_OBJ_GFX_ZPICHU_DOLL

#define EVENT_OBJ_ID_PLAYER 0xFF
#define EVENT_OBJ_ID_CAMERA 0x7F

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
