#ifndef GUARD_CONSTANTS_EVENTOBJPAL_H
#define GUARD_CONSTANTS_EVENTOBJPAL_H

#define PAL_NPC_RED 0x1
#define PAL_NPC_BLUE 0x2
#define PAL_NPC_GREEN 0x3
#define PAL_NPC_BROWN 0x4
#define PAL_NPC_PINK 0x5
#define PAL_NPC_SILVER 0x6
#define PAL_NPC_TREE 0x7
#define PAL_NPC_ROCK 0x8


#endif // GUARD_CONSTANTS_EVENTOBJPAL_H
