#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

// Map Group 0
#define MAP_NEW_BARK_TOWN          (0 | (0 << 8))
#define MAP_CHERRYGROVE_CITY       (1 | (0 << 8))
#define MAP_VIOLET_CITY            (2 | (0 << 8))
#define MAP_AZALEA_TOWN            (3 | (0 << 8))
#define MAP_GOLDENROD_CITY         (4 | (0 << 8))
#define MAP_ECRUTEAK_CITY          (5 | (0 << 8))
#define MAP_OLIVINE_CITY           (6 | (0 << 8))
#define MAP_CIANWOOD_CITY          (7 | (0 << 8))
#define MAP_MAHOGANY_TOWN          (8 | (0 << 8))
#define MAP_BLACKTHORN_CITY        (9 | (0 << 8))
#define MAP_LAKE_OF_RAGE           (10 | (0 << 8))
#define MAP_RUINS_OF_ALPH_EXTERIOR (11 | (0 << 8))
#define MAP_ROUTE29                (12 | (0 << 8))
#define MAP_ROUTE30                (13 | (0 << 8))
#define MAP_ROUTE31                (14 | (0 << 8))
#define MAP_ROUTE32                (15 | (0 << 8))
#define MAP_ROUTE33                (16 | (0 << 8))
#define MAP_ROUTE34                (17 | (0 << 8))
#define MAP_ROUTE35                (18 | (0 << 8))
#define MAP_ROUTE36                (19 | (0 << 8))
#define MAP_ROUTE37                (20 | (0 << 8))
#define MAP_ROUTE38                (21 | (0 << 8))
#define MAP_ROUTE39                (22 | (0 << 8))
#define MAP_ROUTE40                (23 | (0 << 8))
#define MAP_ROUTE41                (24 | (0 << 8))
#define MAP_ROUTE42                (25 | (0 << 8))
#define MAP_ROUTE43                (26 | (0 << 8))
#define MAP_ROUTE44                (27 | (0 << 8))
#define MAP_ROUTE45                (28 | (0 << 8))
#define MAP_ROUTE46                (29 | (0 << 8))
#define MAP_SILVER_CAVE_EXTERIOR   (30 | (0 << 8))
#define MAP_PALLET_TOWN            (31 | (0 << 8))
#define MAP_VIRIDIAN_CITY          (32 | (0 << 8))
#define MAP_PEWTER_CITY            (33 | (0 << 8))
#define MAP_CERULEAN_CITY          (34 | (0 << 8))
#define MAP_VERMILION_CITY         (35 | (0 << 8))
#define MAP_LAVENDER_TOWN          (36 | (0 << 8))
#define MAP_CELADON_CITY           (37 | (0 << 8))
#define MAP_SAFFRON_CITY           (38 | (0 << 8))
#define MAP_FUCHSIA_CITY           (39 | (0 << 8))
#define MAP_CINNABAR_ISLAND        (40 | (0 << 8))
#define MAP_ROUTE1                 (41 | (0 << 8))
#define MAP_ROUTE2                 (42 | (0 << 8))
#define MAP_ROUTE3                 (43 | (0 << 8))
#define MAP_ROUTE4                 (44 | (0 << 8))
#define MAP_ROUTE5                 (45 | (0 << 8))
#define MAP_ROUTE6                 (46 | (0 << 8))
#define MAP_ROUTE7                 (47 | (0 << 8))
#define MAP_ROUTE8                 (48 | (0 << 8))
#define MAP_ROUTE9                 (49 | (0 << 8))
#define MAP_ROUTE10                (50 | (0 << 8))
#define MAP_ROUTE11                (51 | (0 << 8))
#define MAP_ROUTE12                (52 | (0 << 8))
#define MAP_ROUTE13                (53 | (0 << 8))
#define MAP_ROUTE14                (54 | (0 << 8))
#define MAP_ROUTE15                (55 | (0 << 8))
#define MAP_ROUTE16                (56 | (0 << 8))
#define MAP_ROUTE17                (57 | (0 << 8))
#define MAP_ROUTE18                (58 | (0 << 8))
#define MAP_ROUTE19                (59 | (0 << 8))
#define MAP_ROUTE20                (60 | (0 << 8))
#define MAP_ROUTE21                (61 | (0 << 8))
#define MAP_ROUTE22                (62 | (0 << 8))
#define MAP_ROUTE23                (63 | (0 << 8))
#define MAP_ROUTE24                (64 | (0 << 8))
#define MAP_ROUTE25                (65 | (0 << 8))
#define MAP_ROUTE26                (66 | (0 << 8))
#define MAP_ROUTE27                (67 | (0 << 8))
#define MAP_ROUTE28                (68 | (0 << 8))

// Map Group 1
#define MAP_NEW_BARK_TOWN_PLAYERS_HOUSE_1F (0 | (1 << 8))
#define MAP_NEW_BARK_TOWN_PLAYERS_HOUSE_2F (1 | (1 << 8))
#define MAP_NEW_BARK_TOWN_PROF_ELMS_HOUSE  (2 | (1 << 8))
#define MAP_NEW_BARK_TOWN_HOUSE            (3 | (1 << 8))
#define MAP_NEW_BARK_TOWN_PROF_ELMS_LAB    (4 | (1 << 8))

// Map Group 2
#define MAP_CHERRYGROVE_CITY_HOUSE1            (0 | (2 << 8))
#define MAP_CHERRYGROVE_CITY_HOUSE2            (1 | (2 << 8))
#define MAP_CHERRYGROVE_CITY_GUIDE_GENTS_HOUSE (2 | (2 << 8))
#define MAP_CHERRYGROVE_CITY_POKEMON_CENTER_1F (3 | (2 << 8))
#define MAP_CHERRYGROVE_CITY_POKEMON_CENTER_2F (4 | (2 << 8))
#define MAP_CHERRYGROVE_CITY_MART              (5 | (2 << 8))

// Map Group 3
#define MAP_VIOLET_CITY_EARLS_POKEMON_ACADEMY (0 | (3 << 8))
#define MAP_VIOLET_CITY_GYM                   (1 | (3 << 8))
#define MAP_VIOLET_CITY_HOUSE1                (2 | (3 << 8))
#define MAP_VIOLET_CITY_HOUSE2                (3 | (3 << 8))
#define MAP_VIOLET_CITY_POKEMON_CENTER_1F     (4 | (3 << 8))
#define MAP_VIOLET_CITY_POKEMON_CENTER_2F     (5 | (3 << 8))
#define MAP_VIOLET_CITY_MART                  (6 | (3 << 8))

// Map Group 4
#define MAP_AZALEA_TOWN_CHARCOAL_KILN     (0 | (4 << 8))
#define MAP_AZALEA_TOWN_POKEMON_CENTER_1F (1 | (4 << 8))
#define MAP_AZALEA_TOWN_POKEMON_CENTER_2F (2 | (4 << 8))
#define MAP_AZALEA_TOWN_GYM               (3 | (4 << 8))
#define MAP_AZALEA_TOWN_KURTS_HOUSE       (4 | (4 << 8))
#define MAP_AZALEA_TOWN_MART              (5 | (4 << 8))

// Map Group 5
#define MAP_GOLDENROD_CITY_POKEMON_CENTER_1F                 (0 | (5 << 8))
#define MAP_GOLDENROD_CITY_POKEMON_CENTER_2F                 (1 | (5 << 8))
#define MAP_GOLDENROD_CITY_GYM                               (2 | (5 << 8))
#define MAP_GOLDENROD_CITY_HOUSE1                            (3 | (5 << 8))
#define MAP_GOLDENROD_CITY_HOUSE2                            (4 | (5 << 8))
#define MAP_GOLDENROD_CITY_NAME_RATERS_HOUSE                 (5 | (5 << 8))
#define MAP_GOLDENROD_CITY_BILLS_FAMILYS_HOUSE               (6 | (5 << 8))
#define MAP_GOLDENROD_CITY_FLOWER_SHOP                       (7 | (5 << 8))
#define MAP_GOLDENROD_CITY_BIKE_SHOP                         (8 | (5 << 8))
#define MAP_GOLDENROD_CITY_GAME_CORNER                       (9 | (5 << 8))
#define MAP_GOLDENROD_CITY_MAGNET_TRAIN_STATION              (10 | (5 << 8))
#define MAP_GOLDENROD_CITY_UNDERGROUND_SWITCH_ROOM_ENTRANCES (11 | (5 << 8))
#define MAP_GOLDENROD_CITY_UNDERGROUND                       (12 | (5 << 8))
#define MAP_GOLDENROD_CITY_UNDERGROUND_WAREHOUSE             (13 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_B1F              (14 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_1F               (15 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_2F               (16 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_3F               (17 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_4F               (18 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_5F               (19 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_6F               (20 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_ROOFTOP          (21 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_ELEVATOR         (22 | (5 << 8))

// Map Group 6
#define MAP_ECRUTEAK_CITY_POKEMON_CENTER_1F (0 | (6 << 8))
#define MAP_ECRUTEAK_CITY_POKEMON_CENTER_2F (1 | (6 << 8))
#define MAP_ECRUTEAK_CITY_MART              (2 | (6 << 8))
#define MAP_ECRUTEAK_CITY_GYM               (3 | (6 << 8))
#define MAP_ECRUTEAK_CITY_HOUSE1            (4 | (6 << 8))
#define MAP_ECRUTEAK_CITY_HOUSE2            (5 | (6 << 8))
#define MAP_ECRUTEAK_CITY_DANCE_THEATER     (6 | (6 << 8))
#define MAP_ECRUTEAK_CITY_TIN_TOWER_GATE    (7 | (6 << 8))
#define MAP_ECRUTEAK_CITY_WISE_TRIOS_ROOM   (8 | (6 << 8))

// Map Group 7
#define MAP_OLIVINE_CITY_POKEMON_CENTER_1F (0 | (7 << 8))
#define MAP_OLIVINE_CITY_POKEMON_CENTER_2F (1 | (7 << 8))
#define MAP_OLIVINE_CITY_MART              (2 | (7 << 8))
#define MAP_OLIVINE_CITY_GYM               (3 | (7 << 8))
#define MAP_OLIVINE_CITY_HOUSE1            (4 | (7 << 8))
#define MAP_OLIVINE_CITY_HOUSE2            (5 | (7 << 8))
#define MAP_OLIVINE_CITY_HOUSE3            (6 | (7 << 8))
#define MAP_OLIVINE_CITY_CAFE              (7 | (7 << 8))
#define MAP_OLIVINE_CITY_PORT_PASSAGE      (8 | (7 << 8))
#define MAP_OLIVINE_CITY_PORT              (9 | (7 << 8))

// Map Group 8
#define MAP_CIANWOOD_CITY_POKEMON_CENTER_1F (0 | (8 << 8))
#define MAP_CIANWOOD_CITY_POKEMON_CENTER_2F (1 | (8 << 8))
#define MAP_CIANWOOD_CITY_GYM               (2 | (8 << 8))
#define MAP_CIANWOOD_CITY_HOUSE             (3 | (8 << 8))
#define MAP_CIANWOOD_CITY_PHOTO_STUDIO      (4 | (8 << 8))
#define MAP_CIANWOOD_CITY_PHARMACY          (5 | (8 << 8))
#define MAP_CIANWOOD_CITY_MANIAS_HOUSE      (6 | (8 << 8))
#define MAP_CIANWOOD_CITY_POKE_SEERS_HOUSE  (7 | (8 << 8))

// Map Group 9
#define MAP_MAHOGANY_TOWN_POKEMON_CENTER_1F (0 | (9 << 8))
#define MAP_MAHOGANY_TOWN_POKEMON_CENTER_2F (1 | (9 << 8))
#define MAP_MAHOGANY_TOWN_GYM               (2 | (9 << 8))
#define MAP_MAHOGANY_TOWN_HOUSE             (3 | (9 << 8))
#define MAP_MAHOGANY_TOWN_SHOP              (4 | (9 << 8))

// Map Group 10
#define MAP_BLACKTHORN_CITY_POKEMON_CENTER_1F   (0 | (10 << 8))
#define MAP_BLACKTHORN_CITY_POKEMON_CENTER_2F   (1 | (10 << 8))
#define MAP_BLACKTHORN_CITY_MART                (2 | (10 << 8))
#define MAP_BLACKTHORN_CITY_GYM_1F              (3 | (10 << 8))
#define MAP_BLACKTHORN_CITY_GYM_2F              (4 | (10 << 8))
#define MAP_BLACKTHORN_CITY_HOUSE1              (5 | (10 << 8))
#define MAP_BLACKTHORN_CITY_HOUSE2              (6 | (10 << 8))
#define MAP_BLACKTHORN_CITY_MOVE_DELETERS_HOUSE (7 | (10 << 8))

// Map Group 11
#define MAP_LAKE_OF_RAGE_HIDDEN_POWER_HOUSE  (0 | (11 << 8))
#define MAP_LAKE_OF_RAGE_FISHING_GURUS_HOUSE (1 | (11 << 8))

// Map Group 12
#define MAP_RUINS_OF_ALPH_RESEARCH_CENTER (0 | (12 << 8))

// Map Group 13
#define MAP_ROUTE29_GATE (0 | (13 << 8))

// Map Group 14
#define MAP_ROUTE30_BERRY_HOUSE       (0 | (14 << 8))
#define MAP_ROUTE30_MR_POKEMONS_HOUSE (1 | (14 << 8))

// Map Group 15
#define MAP_ROUTE31_GATE (0 | (15 << 8))

// Map Group 16
#define MAP_ROUTE32_GATE              (0 | (16 << 8))
#define MAP_ROUTE32_POKEMON_CENTER_1F (1 | (16 << 8))
#define MAP_ROUTE32_POKEMON_CENTER_2F (2 | (16 << 8))

// Map Group 17
#define MAP_ROUTE34_GATE1            (0 | (17 << 8))
#define MAP_ROUTE34_GATE2            (1 | (17 << 8))
#define MAP_ROUTE34_POKEMON_DAY_CARE (2 | (17 << 8))

// Map Group 18
#define MAP_ROUTE35_GATE               (0 | (18 << 8))
#define MAP_ROUTE35_NATIONAL_PARK_GATE (1 | (18 << 8))

// Map Group 19
#define MAP_ROUTE36_GATE               (0 | (19 << 8))
#define MAP_ROUTE36_NATIONAL_PARK_GATE (1 | (19 << 8))

// Map Group 20
#define MAP_ROUTE38_GATE (0 | (20 << 8))

// Map Group 21
#define MAP_ROUTE39_MOO_MOO_FARM_HOUSE (0 | (21 << 8))
#define MAP_ROUTE39_MOO_MOO_FARM_BARN  (1 | (21 << 8))

// Map Group 22
#define MAP_ROUTE40_BATTLE_TOWER_GATE (0 | (22 << 8))

// Map Group 23
#define MAP_ROUTE42_GATE (0 | (23 << 8))

// Map Group 24
#define MAP_ROUTE43_GATE1 (0 | (24 << 8))
#define MAP_ROUTE43_GATE2 (1 | (24 << 8))

// Map Group 25
#define MAP_SILVER_CAVE_EXTERIOR_POKEMON_CENTER_1F (0 | (25 << 8))
#define MAP_SILVER_CAVE_EXTERIOR_POKEMON_CENTER_2F (1 | (25 << 8))

// Map Group 26
#define MAP_DARK_CAVE_VIOLET                        (0 | (26 << 8))
#define MAP_DARK_CAVE_BLACKTHORN                    (1 | (26 << 8))
#define MAP_SPROUT_TOWER_1F                         (2 | (26 << 8))
#define MAP_SPROUT_TOWER_2F                         (3 | (26 << 8))
#define MAP_SPROUT_TOWER_3F                         (4 | (26 << 8))
#define MAP_RUINS_OF_ALPH_MAIN_CHAMBER              (5 | (26 << 8))
#define MAP_RUINS_OF_ALPH_KABUTO_PUZZLE_CHAMBER     (6 | (26 << 8))
#define MAP_RUINS_OF_ALPH_KABUTO_ITEM_ROOM          (7 | (26 << 8))
#define MAP_RUINS_OF_ALPH_KABUTO_WORD_ROOM          (8 | (26 << 8))
#define MAP_RUINS_OF_ALPH_AERODACTYL_PUZZLE_CHAMBER (9 | (26 << 8))
#define MAP_RUINS_OF_ALPH_AERODACTYL_ITEM_ROOM      (10 | (26 << 8))
#define MAP_RUINS_OF_ALPH_AERODACTYL_WORD_ROOM      (11 | (26 << 8))
#define MAP_RUINS_OF_ALPH_OMANYTE_PUZZLE_CHAMBER    (12 | (26 << 8))
#define MAP_RUINS_OF_ALPH_OMANYTE_ITEM_ROOM         (13 | (26 << 8))
#define MAP_RUINS_OF_ALPH_OMANYTE_WORD_ROOM         (14 | (26 << 8))
#define MAP_RUINS_OF_ALPH_HO_OH_PUZZLE_CHAMBER      (15 | (26 << 8))
#define MAP_RUINS_OF_ALPH_HO_OH_ITEM_ROOM           (16 | (26 << 8))
#define MAP_RUINS_OF_ALPH_HO_OH_WORD_ROOM           (17 | (26 << 8))
#define MAP_UNION_CAVE_1F                           (18 | (26 << 8))
#define MAP_UNION_CAVE_B1F                          (19 | (26 << 8))
#define MAP_UNION_CAVE_B2F                          (20 | (26 << 8))
#define MAP_SLOWPOKE_WELL_B1F                       (21 | (26 << 8))
#define MAP_SLOWPOKE_WELL_B2F                       (22 | (26 << 8))
#define MAP_ILEX_FOREST                             (23 | (26 << 8))
#define MAP_RADIO_TOWER_1F                          (24 | (26 << 8))
#define MAP_RADIO_TOWER_2F                          (25 | (26 << 8))
#define MAP_RADIO_TOWER_3F                          (26 | (26 << 8))
#define MAP_RADIO_TOWER_4F                          (27 | (26 << 8))
#define MAP_RADIO_TOWER_5F                          (28 | (26 << 8))
#define MAP_NATIONAL_PARK                           (29 | (26 << 8))
#define MAP_BURNED_TOWER_1F                         (30 | (26 << 8))
#define MAP_BURNED_TOWER_B1F                        (31 | (26 << 8))
#define MAP_TIN_TOWER_1F                            (32 | (26 << 8))
#define MAP_TIN_TOWER_2F                            (33 | (26 << 8))
#define MAP_TIN_TOWER_3F                            (34 | (26 << 8))
#define MAP_TIN_TOWER_4F                            (35 | (26 << 8))
#define MAP_TIN_TOWER_5F                            (36 | (26 << 8))
#define MAP_TIN_TOWER_6F                            (37 | (26 << 8))
#define MAP_TIN_TOWER_7F                            (38 | (26 << 8))
#define MAP_TIN_TOWER_8F                            (39 | (26 << 8))
#define MAP_TIN_TOWER_9F                            (40 | (26 << 8))
#define MAP_TIN_TOWER_ROOF                          (41 | (26 << 8))
#define MAP_LIGHTHOUSE_1F                           (42 | (26 << 8))
#define MAP_LIGHTHOUSE_2F                           (43 | (26 << 8))
#define MAP_LIGHTHOUSE_3F                           (44 | (26 << 8))
#define MAP_LIGHTHOUSE_4F                           (45 | (26 << 8))
#define MAP_LIGHTHOUSE_5F                           (46 | (26 << 8))
#define MAP_LIGHTHOUSE_6F                           (47 | (26 << 8))
#define MAP_WHIRL_ISLANDS_1F_NE                     (48 | (26 << 8))
#define MAP_WHIRL_ISLANDS_1F_NW                     (49 | (26 << 8))
#define MAP_WHIRL_ISLANDS_1F_SE                     (50 | (26 << 8))
#define MAP_WHIRL_ISLANDS_1F_SW                     (51 | (26 << 8))
#define MAP_WHIRL_ISLANDS_B1F                       (52 | (26 << 8))
#define MAP_WHIRL_ISLANDS_B2F                       (53 | (26 << 8))
#define MAP_WHIRL_ISLANDS_CAVE                      (54 | (26 << 8))
#define MAP_WHIRL_ISLANDS_LUGIAS_CHAMBER            (55 | (26 << 8))
#define MAP_MT_MORTAR_1F_OUTER                      (56 | (26 << 8))
#define MAP_MT_MORTAR_1F_INNER                      (57 | (26 << 8))
#define MAP_MT_MORTAR_2F                            (58 | (26 << 8))
#define MAP_MT_MORTAR_B1F                           (59 | (26 << 8))
#define MAP_TEAM_ROCKET_BASE_B1F                    (60 | (26 << 8))
#define MAP_TEAM_ROCKET_BASE_B2F                    (61 | (26 << 8))
#define MAP_TEAM_ROCKET_BASE_B3F                    (62 | (26 << 8))
#define MAP_ICE_PATH_1F                             (63 | (26 << 8))
#define MAP_ICE_PATH_B1F                            (64 | (26 << 8))
#define MAP_ICE_PATH_B2F_MAHOGANY                   (65 | (26 << 8))
#define MAP_ICE_PATH_B2F_BLACKTHORN                 (66 | (26 << 8))
#define MAP_ICE_PATH_B3F                            (67 | (26 << 8))
#define MAP_DRAGONS_DEN_ENTRANCE                    (68 | (26 << 8))
#define MAP_DRAGONS_DEN                             (69 | (26 << 8))
#define MAP_DRAGONS_DEN_DRAGON_SHRINE               (70 | (26 << 8))
#define MAP_FAST_SHIP_1F                            (71 | (26 << 8))
#define MAP_FAST_SHIP_B1F                           (72 | (26 << 8))
#define MAP_FAST_SHIP_CABINS_NNW_NNE_NE             (73 | (26 << 8))
#define MAP_FAST_SHIP_CABINS_SE_SSE_CAPTAINS        (74 | (26 << 8))
#define MAP_FAST_SHIP_CABINS_SW_SSW_NW              (75 | (26 << 8))
#define MAP_SILVER_CAVE_ROOM1                       (76 | (26 << 8))
#define MAP_SILVER_CAVE_ROOM2                       (77 | (26 << 8))
#define MAP_SILVER_CAVE_ROOM3                       (78 | (26 << 8))
#define MAP_SILVER_CAVE_ITEM_ROOMS                  (79 | (26 << 8))
#define MAP_BATTLE_TOWER_EXTERIOR                   (80 | (26 << 8))
#define MAP_BATTLE_TOWER_LOBBY                      (81 | (26 << 8))
#define MAP_BATTLE_TOWER_ELEVATOR                   (82 | (26 << 8))
#define MAP_BATTLE_TOWER_HALLWAY                    (83 | (26 << 8))
#define MAP_BATTLE_TOWER_BATTLE_ROOM                (84 | (26 << 8))
#define MAP_TOHJO_FALLS                             (85 | (26 << 8))
#define MAP_VICTORY_ROAD_GATE                       (86 | (26 << 8))
#define MAP_VICTORY_ROAD                            (87 | (26 << 8))

// Map Group 27
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (27 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (27 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (27 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (27 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (27 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (27 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (27 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (27 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (27 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (27 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (27 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (27 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (27 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (27 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (27 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (27 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (27 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (27 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (27 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (27 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (27 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (27 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (27 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (27 << 8))
#define MAP_SINGLE_BATTLE_COLOSSEUM  (24 | (27 << 8))
#define MAP_TRADE_CENTER             (25 | (27 << 8))
#define MAP_RECORD_CORNER            (26 | (27 << 8))
#define MAP_DOUBLE_BATTLE_COLOSSEUM  (27 | (27 << 8))
#define MAP_LINK_CONTEST_ROOM1       (28 | (27 << 8))
#define MAP_UNKNOWN_MAP_25_29        (29 | (27 << 8))
#define MAP_UNKNOWN_MAP_25_30        (30 | (27 << 8))
#define MAP_UNKNOWN_MAP_25_31        (31 | (27 << 8))
#define MAP_UNKNOWN_MAP_25_32        (32 | (27 << 8))
#define MAP_UNKNOWN_MAP_25_33        (33 | (27 << 8))
#define MAP_UNKNOWN_MAP_25_34        (34 | (27 << 8))
#define MAP_LINK_CONTEST_ROOM2       (35 | (27 << 8))
#define MAP_LINK_CONTEST_ROOM3       (36 | (27 << 8))
#define MAP_LINK_CONTEST_ROOM4       (37 | (27 << 8))
#define MAP_LINK_CONTEST_ROOM5       (38 | (27 << 8))
#define MAP_LINK_CONTEST_ROOM6       (39 | (27 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (27 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (27 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (27 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (27 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (27 << 8))
#define MAP_UNION_ROOM               (60 | (27 << 8))

// Map Group 28
#define MAP_SAFARI_ZONE_NORTHWEST                                (0 | (28 << 8))
#define MAP_SAFARI_ZONE_NORTH                                    (1 | (28 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                                (2 | (28 << 8))
#define MAP_SAFARI_ZONE_SOUTH                                    (3 | (28 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                         (4 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY                   (5 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR                (6 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR                (7 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM             (8 | (28 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                             (9 | (28 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                             (10 | (28 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                               (11 | (28 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                                (12 | (28 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                                (13 | (28 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                         (14 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM       (15 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR2               (16 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM2            (17 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY                    (18 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR                 (19 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM          (20 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM              (21 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY                  (22 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR               (23 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM            (24 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY                 (25 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_EMPTY_SQUARE          (26 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP                   (27 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY                   (28 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR                (29 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM             (30 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY                 (31 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM       (32 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM           (33 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY                    (34 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR                 (35 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM          (36 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_RANDOM_ROOM1             (37 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_RANDOM_ROOM2             (38 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_RANDOM_ROOM3             (39 | (28 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                         (40 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                              (41 | (28 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_POINT_EXCHANGE_SERVICE_CORNER (42 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                              (43 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                              (44 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                              (45 | (28 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                         (46 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                              (47 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                              (48 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                              (49 | (28 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                       (50 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                              (51 | (28 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                              (52 | (28 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F                    (53 | (28 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F                    (54 | (28 << 8))
#define MAP_BATTLE_FRONTIER_MART                                 (55 | (28 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                              (56 | (28 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                              (57 | (28 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                                (58 | (28 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                                  (59 | (28 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                                (60 | (28 << 8))
#define MAP_TRAINER_HILL_1F                                      (61 | (28 << 8))
#define MAP_TRAINER_HILL_2F                                      (62 | (28 << 8))
#define MAP_TRAINER_HILL_3F                                      (63 | (28 << 8))
#define MAP_TRAINER_HILL_4F                                      (64 | (28 << 8))
#define MAP_TRAINER_HILL_ROOF                                    (65 | (28 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                                  (66 | (28 << 8))
#define MAP_NAVEL_ROCK_HARBOR                                    (67 | (28 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                                  (68 | (28 << 8))
#define MAP_NAVEL_ROCK_B1F                                       (69 | (28 << 8))
#define MAP_NAVEL_ROCK_FORK                                      (70 | (28 << 8))
#define MAP_NAVEL_ROCK_UP1                                       (71 | (28 << 8))
#define MAP_NAVEL_ROCK_UP2                                       (72 | (28 << 8))
#define MAP_NAVEL_ROCK_UP3                                       (73 | (28 << 8))
#define MAP_NAVEL_ROCK_UP4                                       (74 | (28 << 8))
#define MAP_NAVEL_ROCK_TOP                                       (75 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN01                                    (76 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN02                                    (77 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN03                                    (78 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN04                                    (79 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN05                                    (80 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN06                                    (81 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN07                                    (82 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN08                                    (83 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN09                                    (84 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN10                                    (85 | (28 << 8))
#define MAP_NAVEL_ROCK_DOWN11                                    (86 | (28 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                                    (87 | (28 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                                (88 | (28 << 8))

// Map Group 29
#define MAP_ROUTE27_HOUSE (0 | (29 << 8))

// Map Group 30
#define MAP_ROUTE26_HOUSE1 (0 | (30 << 8))
#define MAP_ROUTE26_HOUSE2 (1 | (30 << 8))

// Map Group 31
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F (0 | (31 << 8))
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F (1 | (31 << 8))
#define MAP_INDIGO_PLATEAU_WILLS_ROOM        (2 | (31 << 8))
#define MAP_INDIGO_PLATEAU_KOGAS_ROOM        (3 | (31 << 8))
#define MAP_INDIGO_PLATEAU_BRUNOS_ROOM       (4 | (31 << 8))
#define MAP_INDIGO_PLATEAU_KARENS_ROOM       (5 | (31 << 8))
#define MAP_INDIGO_PLATEAU_LANCES_ROOM       (6 | (31 << 8))
#define MAP_INDIGO_PLATEAU_HALL_OF_FAME      (7 | (31 << 8))

// Map Group 32
#define MAP_ROUTE28_HOUSE (0 | (32 << 8))

// Map Group 33
#define MAP_PALLET_TOWN_REDS_HOUSE_1F (0 | (33 << 8))
#define MAP_PALLET_TOWN_REDS_HOUSE_2F (1 | (33 << 8))
#define MAP_PALLET_TOWN_BLUES_HOUSE   (2 | (33 << 8))
#define MAP_PALLET_TOWN_PROF_OAKS_LAB (3 | (33 << 8))

// Map Group 34
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (34 << 8))

// Map Group 35
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F                (0 | (35 << 8))
#define MAP_ROUTE119_HOUSE                               (1 | (35 << 8))
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE       (2 | (35 << 8))
#define MAP_LILYCOVE_CITY                                (3 | (35 << 8))
#define MAP_MOSSDEEP_CITY                                (4 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY                              (5 | (35 << 8))
#define MAP_EVER_GRANDE_CITY                             (6 | (35 << 8))
#define MAP_LAVARIDGE_TOWN                               (7 | (35 << 8))
#define MAP_PACIFIDLOG_TOWN                              (8 | (35 << 8))
#define MAP_ROUTE126                                     (9 | (35 << 8))
#define MAP_ROUTE127                                     (10 | (35 << 8))
#define MAP_ROUTE128                                     (11 | (35 << 8))
#define MAP_ROUTE129                                     (12 | (35 << 8))
#define MAP_ROUTE130                                     (13 | (35 << 8))
#define MAP_ROUTE131                                     (14 | (35 << 8))
#define MAP_ROUTE132                                     (15 | (35 << 8))
#define MAP_ROUTE133                                     (16 | (35 << 8))
#define MAP_ROUTE134                                     (17 | (35 << 8))
#define MAP_UNDERWATER1                                  (18 | (35 << 8))
#define MAP_UNDERWATER2                                  (19 | (35 << 8))
#define MAP_UNDERWATER3                                  (20 | (35 << 8))
#define MAP_UNDERWATER4                                  (21 | (35 << 8))
#define MAP_UNDERWATER5                                  (22 | (35 << 8))
#define MAP_UNDERWATER6                                  (23 | (35 << 8))
#define MAP_UNDERWATER7                                  (24 | (35 << 8))
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE                 (25 | (35 << 8))
#define MAP_ROUTE109_SEASHORE_HOUSE                      (26 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (27 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (28 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (29 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (30 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (31 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (32 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (33 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (34 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (35 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (36 | (35 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (37 | (35 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (38 | (35 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (39 | (35 << 8))
#define MAP_ROUTE104_PROTOTYPE                           (40 | (35 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP  (41 | (35 << 8))
#define MAP_FORTREE_CITY_HOUSE4                          (42 | (35 << 8))
#define MAP_FORTREE_CITY_HOUSE5                          (43 | (35 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP                 (44 | (35 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY            (45 | (35 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR         (46 | (35 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM      (47 | (35 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY             (48 | (35 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR          (49 | (35 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM       (50 | (35 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F                       (51 | (35 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F                       (52 | (35 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F                       (53 | (35 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                        (54 | (35 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F                       (55 | (35 << 8))
#define MAP_LAVARIDGE_TOWN_MART                          (56 | (35 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F             (57 | (35 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F             (58 | (35 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F            (59 | (35 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F            (60 | (35 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1                       (61 | (35 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2                       (62 | (35 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3                       (63 | (35 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4                       (64 | (35 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5                       (65 | (35 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F             (66 | (35 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F             (67 | (35 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F             (68 | (35 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY                  (69 | (35 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL                   (70 | (35 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F              (71 | (35 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F              (72 | (35 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB       (73 | (35 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                         (74 | (35 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE            (75 | (35 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                         (76 | (35 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                         (77 | (35 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                         (78 | (35 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                         (79 | (35 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1                         (80 | (35 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2                         (81 | (35 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F              (82 | (35 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F              (83 | (35 << 8))
#define MAP_MOSSDEEP_CITY_MART                           (84 | (35 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3                         (85 | (35 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE                  (86 | (35 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4                         (87 | (35 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F                (88 | (35 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F                (89 | (35 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F                 (90 | (35 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F                (91 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F            (92 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F            (93 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                         (94 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                       (95 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                       (96 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                       (97 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                       (98 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                       (99 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                       (100 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                       (101 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE       (102 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F      (103 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F     (104 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM                (105 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM                (106 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM                (107 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM                 (108 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM              (109 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1                       (110 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2                       (111 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3                       (112 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4                       (113 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5                       (114 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F           (115 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME                (116 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F           (117 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F           (118 | (35 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F           (119 | (35 << 8))
#define MAP_ROUTE104_MR_BRINEYS_HOUSE                    (120 | (35 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP            (121 | (35 << 8))
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE             (122 | (35 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP                 (123 | (35 << 8))
#define MAP_ROUTE112_CABLE_CAR_STATION                   (124 | (35 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION                 (125 | (35 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE                (126 | (35 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL               (127 | (35 << 8))
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE                (128 | (35 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE                      (129 | (35 << 8))
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE                (130 | (35 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY             (131 | (35 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR          (132 | (35 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM       (133 | (35 << 8))
#define MAP_METEOR_FALLS_B1F_2R                          (134 | (35 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY                   (135 | (35 << 8))
#define MAP_DESERT_RUINS                                 (136 | (35 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                    (137 | (35 << 8))
#define MAP_MT_CHIMNEY                                   (138 | (35 << 8))
#define MAP_JAGGED_PASS                                  (139 | (35 << 8))
#define MAP_FIERY_PATH                                   (140 | (35 << 8))
#define MAP_MT_PYRE_1F                                   (141 | (35 << 8))
#define MAP_MT_PYRE_2F                                   (142 | (35 << 8))
#define MAP_MT_PYRE_3F                                   (143 | (35 << 8))
#define MAP_MT_PYRE_4F                                   (144 | (35 << 8))
#define MAP_MT_PYRE_5F                                   (145 | (35 << 8))
#define MAP_MT_PYRE_6F                                   (146 | (35 << 8))
#define MAP_MT_PYRE_EXTERIOR                             (147 | (35 << 8))
#define MAP_MT_PYRE_SUMMIT                               (148 | (35 << 8))
#define MAP_AQUA_HIDEOUT_1F                              (149 | (35 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                      (150 | (35 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                            (151 | (35 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3     (152 | (35 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                           (153 | (35 << 8))
#define MAP_VICTORY_ROAD_1F                              (154 | (35 << 8))
#define MAP_VICTORY_ROAD_B1F                             (155 | (35 << 8))
#define MAP_VICTORY_ROAD_B2F                             (156 | (35 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM            (157 | (35 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM               (158 | (35 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM              (159 | (35 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM               (160 | (35 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM           (161 | (35 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM              (162 | (35 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                        (163 | (35 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                          (164 | (35 << 8))
#define MAP_ABANDONED_SHIP_DECK                          (165 | (35 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F                  (166 | (35 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                      (167 | (35 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F                 (168 | (35 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                     (169 | (35 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                    (170 | (35 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1                   (171 | (35 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                      (172 | (35 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                     (173 | (35 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE               (174 | (35 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2                   (175 | (35 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS        (176 | (35 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS            (177 | (35 << 8))
#define MAP_ISLAND_CAVE                                  (178 | (35 << 8))
#define MAP_ANCIENT_TOMB                                 (179 | (35 << 8))
#define MAP_UNDERWATER_ROUTE134                          (180 | (35 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                    (181 | (35 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                    (182 | (35 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                    (183 | (35 << 8))
#define MAP_SCORCHED_SLAB                                (184 | (35 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                          (185 | (35 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                           (186 | (35 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM                 (187 | (35 << 8))
#define MAP_MAGMA_HIDEOUT_1F                             (188 | (35 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                          (189 | (35 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                          (190 | (35 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                          (191 | (35 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                          (192 | (35 << 8))
#define MAP_MAGMA_HIDEOUT_4F                             (193 | (35 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                          (194 | (35 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                          (195 | (35 << 8))
#define MAP_MIRAGE_TOWER_1F                              (196 | (35 << 8))
#define MAP_MIRAGE_TOWER_2F                              (197 | (35 << 8))
#define MAP_MIRAGE_TOWER_3F                              (198 | (35 << 8))
#define MAP_MIRAGE_TOWER_4F                              (199 | (35 << 8))
#define MAP_DESERT_UNDERPASS                             (200 | (35 << 8))
#define MAP_ARTISAN_CAVE_B1F                             (201 | (35 << 8))
#define MAP_ARTISAN_CAVE_1F                              (202 | (35 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                       (203 | (35 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                         (204 | (35 << 8))
#define MAP_MARINE_CAVE_END                              (205 | (35 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                          (206 | (35 << 8))
#define MAP_TERRA_CAVE_END                               (207 | (35 << 8))
#define MAP_ALTERING_CAVE                                (208 | (35 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                    (209 | (35 << 8))
#define MAP_ROUTE113_GLASS_WORKSHOP                      (210 | (35 << 8))

#define MAP_GROUPS_COUNT 36

#endif  // GUARD_CONSTANTS_MAP_GROUPS_H
