#ifndef GUARD_CONSTANTS_TILESETPAL_H
#define GUARD_CONSTANTS_TILESETPAL_H

#define PAL_CYCLE 0x0
#define PAL_MORN 0x3
#define PAL_DAY 0x1
#define PAL_NITE 0x2
#define PAL_INDOOR 0x1
#define PAL_DUNGEON_NITE 0x2
#define PAL_DUNGEON_DAY 0x3
#define PAL_DUNGEON_DARK 0x4


#endif // GUARD_CONSTANTS_TILESETPAL_H