BattleTower_Exterior:
	.4byte BattleTower_Exterior_Layout
	.4byte BattleTower_Exterior_MapEvents
	.4byte BattleTower_Exterior_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_BATTLE_TOWER_EXTERIOR
	.byte MAPSEC_BATTLE_FRONTIER
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_ROUTE
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

