CherrygroveCity:
	.4byte CherrygroveCity_Layout
	.4byte CherrygroveCity_MapEvents
	.4byte CherrygroveCity_MapScripts
	.4byte CherrygroveCity_MapConnections
	.2byte MUS_MACHI_S4
	.2byte LAYOUT_CHERRYGROVE_CITY
	.byte MAPSEC_CHERRYGROVE_CITY
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_TOWN
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

