CherrygroveCity::
	.4byte CherrygroveCity_Layout
	.4byte CherrygroveCity_MapEvents
	.4byte CherrygroveCity_MapScripts
	.4byte CherrygroveCity_MapConnections
	.2byte MUS_MACHI_S4
	.2byte 11
	.byte MAPSEC_CHERRYGROVE_CITY
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_TOWN
	.2byte PAL_CYCLE
	map_header_flags allow_bike=1, allow_escape_rope=0, allow_run=0, show_map_name=TRUE
	.byte MAP_BATTLE_SCENE_NORMAL
