gText_ConfirmSave:: @ 82C87B4
	.string "Would you like to\n"
	.string "save the game?$"

gText_AlreadySavedFile:: @ 82C87D5
	.string "There is already a\n"
	.string "save file. Is it\l"
	.string "OK to overwrite?$"

gText_SavingDontTurnOff:: @ 82C8810
	.string "SAVING… DON’T TURN\n"
	.string "OFF THE POWER.$"

gText_PlayerSavedGame:: @ 82C8832
	.string "{PLAYER} saved\n"
	.string "the game.$"

gText_DifferentSaveFile:: @ 82C8845
	.string "There is another\n"
	.string "save file. Is it\l"
	.string "OK to overwrite?$"

gText_SaveError:: @ 82C892A
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower:: @ 82C8959
	.string "SAVING… DON’T TURN\n"
	.string "OFF THE POWER.$"
