VioletCity_EarlsPokemonAcademy::
	.4byte VioletCity_EarlsPokemonAcademy_Layout
	.4byte VioletCity_EarlsPokemonAcademy_MapEvents
	.4byte VioletCity_EarlsPokemonAcademy_MapScripts
	.4byte 0x0
	.2byte MUS_RG_NANA67
	.2byte 95
	.byte MAPSEC_VIOLET_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte PAL_INDOOR
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
