Route34_PokemonDayCare_EventObjects::
	object_event 1, EVENT_OBJ_GFX_OLD_WOMAN, 0, 2, 2, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, Route117_PokemonDayCare_EventScript_291D11, 0

Route34_PokemonDayCare_MapWarps::
	warp_def 2, 7, 0, 4, MAP_ROUTE34
	warp_def 3, 7, 0, 4, MAP_ROUTE34
	warp_def 0, 5, 3, 2, MAP_ROUTE34
	warp_def 0, 6, 3, 3, MAP_ROUTE34

Route34_PokemonDayCare_MapEvents::
	map_events Route34_PokemonDayCare_EventObjects, Route34_PokemonDayCare_MapWarps, 0x0, 0x0
