VioletCity_House2_EventObjects::
	object_event 1, EVENT_OBJ_GFX_POKEFAN_M, 4, 2, 3, 3, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, PetalburgCity_House2_EventScript_2078F3, 0
	object_event 2, EVENT_OBJ_GFX_YOUNGSTER, 1, 6, 5, 3, MOVEMENT_TYPE_WANDER_UP_AND_DOWN, 0, 2, 0, 0, PetalburgCity_House2_EventScript_2078FC, 0

VioletCity_House2_MapWarps::
	warp_def 3, 7, 0, 4, MAP_VIOLET_CITY
	warp_def 4, 7, 0, 4, MAP_VIOLET_CITY

VioletCity_House2_MapEvents::
	map_events VioletCity_House2_EventObjects, VioletCity_House2_MapWarps, 0x0, 0x0
