CianwoodCity_Pharmacy_EventObjects::
	object_event 1, EVENT_OBJ_GFX_PHARMACIST, PAL_NPC_RED, 2, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, FallarborTown_House2_EventScript_201383, 0

CianwoodCity_Pharmacy_MapWarps::
	warp_def 2, 7, 0, 3, MAP_CIANWOOD_CITY
	warp_def 3, 7, 0, 3, MAP_CIANWOOD_CITY

CianwoodCity_Pharmacy_MapEvents::
	map_events CianwoodCity_Pharmacy_EventObjects, CianwoodCity_Pharmacy_MapWarps, 0x0, 0x0
