EcruteakCity_TinTowerGate::
	.4byte EcruteakCity_TinTowerGate_Layout
	.4byte EcruteakCity_TinTowerGate_MapEvents
	.4byte EcruteakCity_TinTowerGate_MapScripts
	.4byte 0x0
	.2byte MUS_MACHI_S4
	.2byte 68
	.byte MAPSEC_ECRUTEAK_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
