FastShip_Cabins_SE_SSE_Captains::
	.4byte FastShip_Cabins_SE_SSE_Captains_Layout
	.4byte FastShip_Cabins_SE_SSE_Captains_MapEvents
	.4byte FastShip_Cabins_SE_SSE_Captains_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte 2721
	.byte MAPSEC_FAST_SHIP
	.byte FALSE
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_INDOOR
	.2byte PAL_INDOOR
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=TRUE
	.byte MAP_BATTLE_SCENE_NORMAL
