IndigoPlateau_WillsRoom_EventObjects::
	object_event 1, EVENT_OBJ_GFX_WILL, PAL_NPC_RED, 5, 7, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, FALSE, 0, NULL, 0

IndigoPlateau_WillsRoom_MapWarps::
	warp_def 5, 17, 3, 3, MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F
	warp_def 4, 2, 3, 0, MAP_INDIGO_PLATEAU_KOGAS_ROOM
	warp_def 5, 2, 3, 1, MAP_INDIGO_PLATEAU_KOGAS_ROOM

IndigoPlateau_WillsRoom_MapEvents::
	map_events IndigoPlateau_WillsRoom_EventObjects, IndigoPlateau_WillsRoom_MapWarps, 0x0, 0x0
