SilverCave_Exterior::
	.4byte SilverCave_Exterior_Layout
	.4byte SilverCave_Exterior_MapEvents
	.4byte SilverCave_Exterior_MapScripts
	.4byte SilverCave_Exterior_MapConnections
	.2byte MUS_DOORO_X4
	.2byte 39
	.byte MAPSEC_SILVER_CAVE
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_ROUTE
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=0, allow_run=0, show_map_name=TRUE
	.byte MAP_BATTLE_SCENE_NORMAL
