IndigoPlateau_PokemonCenter_1F::
	.4byte IndigoPlateau_PokemonCenter_1F_Layout
	.4byte IndigoPlateau_PokemonCenter_1F_MapEvents
	.4byte IndigoPlateau_PokemonCenter_1F_MapScripts
	.4byte 0x0
	.2byte MUS_RG_POKECEN
	.2byte 2734
	.byte MAPSEC_INDIGO_PLATEAU
	.byte FALSE
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_INDOOR
	.2byte PAL_INDOOR
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
