TinTower_1F_EventObjects::
	object_event 1, EVENT_OBJ_GFX_SUICUNE, PAL_NPC_BLUE, 9, 9, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, SeafloorCavern_Entrance_EventScript_234485, 0
	object_event 2, EVENT_OBJ_GFX_RAIKOU, PAL_NPC_BROWN, 7, 9, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, SeafloorCavern_Entrance_EventScript_234485, 0
	object_event 3, EVENT_OBJ_GFX_ENTEI, PAL_NPC_RED, 12, 9, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, SeafloorCavern_Entrance_EventScript_234485, 0
	object_event 4, EVENT_OBJ_GFX_SUPER_NERD, PAL_NPC_BLUE, 8, 3, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, SeafloorCavern_Entrance_EventScript_234485, 0
	object_event 5, EVENT_OBJ_GFX_SAGE, 0, 5, 9, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, SeafloorCavern_Entrance_EventScript_234485, 0
	object_event 6, EVENT_OBJ_GFX_SAGE, 0, 11, 11, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, SeafloorCavern_Entrance_EventScript_234485, 0
	object_event 7, EVENT_OBJ_GFX_SAGE, 0, 14, 6, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, SeafloorCavern_Entrance_EventScript_234485, 0
	object_event 8, EVENT_OBJ_GFX_SAGE, 0, 4, 2, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, SeafloorCavern_Entrance_EventScript_234485, 0
	object_event 9, EVENT_OBJ_GFX_SAGE, 0, 9, 1, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, SeafloorCavern_Entrance_EventScript_234485, 0
	object_event 10, EVENT_OBJ_GFX_SAGE, 0, 14, 2, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, SeafloorCavern_Entrance_EventScript_234485, 0

TinTower_1F_MapWarps::
	warp_def 9, 15, 3, 11, MAP_ECRUTEAK_CITY
	warp_def 10, 15, 3, 11, MAP_ECRUTEAK_CITY
	warp_def 10, 2, 3, 1, MAP_TIN_TOWER_2F

TinTower_1F_MapEvents::
	map_events TinTower_1F_EventObjects, TinTower_1F_MapWarps, 0x0, 0x0
