CianwoodCity_PokeSeersHouse_EventObjects::
	object_event 1, EVENT_OBJ_GFX_OLD_WOMAN, PAL_NPC_RED, 2, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, DewfordTown_House2_EventScript_1FE22E, 0

CianwoodCity_PokeSeersHouse_MapWarps::
	warp_def 2, 7, 0, 6, MAP_CIANWOOD_CITY
	warp_def 3, 7, 0, 6, MAP_CIANWOOD_CITY

CianwoodCity_PokeSeersHouse_MapEvents::
	map_events CianwoodCity_PokeSeersHouse_EventObjects, CianwoodCity_PokeSeersHouse_MapWarps, 0x0, 0x0
