GoldenrodCity_NameRatersHouse_EventObjects::
	object_event 1, EVENT_OBJ_GFX_GENTLEMAN, 0, 2, 4, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, SlateportCity_House1_EventScript_209AA5, 0

GoldenrodCity_NameRatersHouse_MapWarps::
	warp_def 2, 7, 0, 7, MAP_GOLDENROD_CITY
	warp_def 3, 7, 0, 7, MAP_GOLDENROD_CITY

GoldenrodCity_NameRatersHouse_MapEvents::
	map_events GoldenrodCity_NameRatersHouse_EventObjects, GoldenrodCity_NameRatersHouse_MapWarps, 0x0, 0x0
