CinnabarIsland:
	.4byte CinnabarIsland_Layout
	.4byte CinnabarIsland_MapEvents
	.4byte CinnabarIsland_MapScripts
	.4byte CinnabarIsland_MapConnections
	.2byte MUS_DAN02
	.2byte LAYOUT_CINNABAR_ISLAND
	.byte MAPSEC_CINNABAR_ISLAND
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_TOWN
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

