IndigoPlateau_HallOfFame_EventObjects::
	object_event 1, EVENT_OBJ_GFX_LANCE, 0, 4, 12, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, FALSE, 0, NULL, 0

IndigoPlateau_HallOfFame_MapWarps::
	warp_def 4, 13, 3, 2, MAP_INDIGO_PLATEAU_LANCES_ROOM
	warp_def 5, 13, 3, 3, MAP_INDIGO_PLATEAU_LANCES_ROOM

IndigoPlateau_HallOfFame_MapEvents::
	map_events IndigoPlateau_HallOfFame_EventObjects, IndigoPlateau_HallOfFame_MapWarps, 0x0, 0x0
