BlackthornCity:
	.4byte BlackthornCity_Layout
	.4byte BlackthornCity_MapEvents
	.4byte BlackthornCity_MapScripts
	.4byte BlackthornCity_MapConnections
	.2byte MUS_RG_NANA45
	.2byte LAYOUT_BLACKTHORN_CITY
	.byte MAPSEC_BLACKTHORN_CITY
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_CITY
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

