BattleFrontier_BattleDomeBattleRoom_EventObjects:
	object_event 1, EVENT_OBJ_GFX_ZREPORTER_M, 0, 5, 4, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 2, EVENT_OBJ_GFX_TWIN, 0, 7, 2, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 3, EVENT_OBJ_GFX_YOUNGSTER, 0, 9, 2, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 4, EVENT_OBJ_GFX_ZBOY_2, 0, 11, 2, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 5, EVENT_OBJ_GFX_ZNINJA_BOY, 0, 16, 2, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 6, EVENT_OBJ_GFX_ZMAN_1, 0, 4, 2, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 7, EVENT_OBJ_GFX_OLD_MAN, 0, 16, 1, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 8, EVENT_OBJ_GFX_ZCAMPER, 0, 8, 1, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 9, EVENT_OBJ_GFX_GYM_GUIDE, 0, 0, 4, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 10, EVENT_OBJ_GFX_FAT_MAN, 0, 12, 1, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 11, EVENT_OBJ_GFX_ZGIRL_2, 0, 13, 2, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 12, EVENT_OBJ_GFX_ZGIRL_1, 0, 10, 2, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 13, EVENT_OBJ_GFX_VAR_1, 0, 4, 9, 4, MOVEMENT_TYPE_FACE_UP, 1, 1, 0, 0, 0x0, 0
	object_event 14, EVENT_OBJ_GFX_ZWOMAN_3, 0, 14, 2, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 15, EVENT_OBJ_GFX_VAR_0, 0, 11, 6, 0, MOVEMENT_TYPE_FACE_LEFT, 1, 1, 0, 0, 0x0, 0

BattleFrontier_BattleDomeBattleRoom_MapEvents::
	map_events BattleFrontier_BattleDomeBattleRoom_EventObjects, 0x0, 0x0, 0x0

