gMapGroup0::
	.4byte NewBarkTown
	.4byte CherrygroveCity
	.4byte VioletCity
	.4byte AzaleaTown
	.4byte GoldenrodCity
	.4byte EcruteakCity
	.4byte OlivineCity
	.4byte CianwoodCity
	.4byte MahoganyTown
	.4byte BlackthornCity
	.4byte LakeOfRage
	.4byte RuinsOfAlph_Exterior
	.4byte Route29
	.4byte Route30
	.4byte Route31
	.4byte Route32
	.4byte Route33
	.4byte Route34
	.4byte Route35
	.4byte Route36
	.4byte Route37
	.4byte Route38
	.4byte Route39
	.4byte Route40
	.4byte Route41
	.4byte Route42
	.4byte Route43
	.4byte Route44
	.4byte Route45
	.4byte Route46
	.4byte SilverCave_Exterior
	.4byte PalletTown
	.4byte ViridianCity
	.4byte PewterCity
	.4byte CeruleanCity
	.4byte VermilionCity
	.4byte LavenderTown
	.4byte CeladonCity
	.4byte SaffronCity
	.4byte FuchsiaCity
	.4byte CinnabarIsland
	.4byte Route1
	.4byte Route2
	.4byte Route3
	.4byte Route4
	.4byte Route5
	.4byte Route6
	.4byte Route7
	.4byte Route8
	.4byte Route9
	.4byte Route10
	.4byte Route11
	.4byte Route12
	.4byte Route13
	.4byte Route14
	.4byte Route15
	.4byte Route16
	.4byte Route17
	.4byte Route18
	.4byte Route19
	.4byte Route20
	.4byte Route21
	.4byte Route22
	.4byte Route23
	.4byte Route24
	.4byte Route25
	.4byte Route26
	.4byte Route27
	.4byte Route28

gMapGroup1::
	.4byte NewBarkTown_PlayersHouse_1F
	.4byte NewBarkTown_PlayersHouse_2F
	.4byte NewBarkTown_ProfElmsHouse
	.4byte NewBarkTown_House
	.4byte NewBarkTown_ProfElmsLab

gMapGroup2::
	.4byte CherrygroveCity_House1
	.4byte CherrygroveCity_House2
	.4byte CherrygroveCity_Guide_Gents_House
	.4byte CherrygroveCity_PokemonCenter_1F
	.4byte CherrygroveCity_PokemonCenter_2F
	.4byte CherrygroveCity_Mart

gMapGroup3::
	.4byte VioletCity_EarlsPokemonAcademy
	.4byte VioletCity_Gym
	.4byte VioletCity_House1
	.4byte VioletCity_House2
	.4byte VioletCity_PokemonCenter_1F
	.4byte VioletCity_PokemonCenter_2F
	.4byte VioletCity_Mart

gMapGroup4::
	.4byte AzaleaTown_CharcoalKiln
	.4byte AzaleaTown_PokemonCenter_1F
	.4byte AzaleaTown_PokemonCenter_2F
	.4byte AzaleaTown_Gym
	.4byte AzaleaTown_KurtsHouse
	.4byte AzaleaTown_Mart

gMapGroup5::
	.4byte GoldenrodCity_PokemonCenter_1F
	.4byte GoldenrodCity_PokemonCenter_2F
	.4byte GoldenrodCity_Gym
	.4byte GoldenrodCity_House1
	.4byte GoldenrodCity_House2
	.4byte GoldenrodCity_NameRatersHouse
	.4byte GoldenrodCity_BillsFamilysHouse
	.4byte GoldenrodCity_FlowerShop
	.4byte GoldenrodCity_BikeShop
	.4byte GoldenrodCity_GameCorner
	.4byte GoldenrodCity_MagnetTrainStation
	.4byte GoldenrodCity_UndergroundSwitchRoomEntrances
	.4byte GoldenrodCity_Underground
	.4byte GoldenrodCity_UndergroundWarehouse
	.4byte GoldenrodCity_DepartmentStore_B1F
	.4byte GoldenrodCity_DepartmentStore_1F
	.4byte GoldenrodCity_DepartmentStore_2F
	.4byte GoldenrodCity_DepartmentStore_3F
	.4byte GoldenrodCity_DepartmentStore_4F
	.4byte GoldenrodCity_DepartmentStore_5F
	.4byte GoldenrodCity_DepartmentStore_6F
	.4byte GoldenrodCity_DepartmentStoreRooftop
	.4byte GoldenrodCity_DepartmentStoreElevator

gMapGroup6::
	.4byte EcruteakCity_PokemonCenter_1F
	.4byte EcruteakCity_PokemonCenter_2F
	.4byte EcruteakCity_Mart
	.4byte EcruteakCity_Gym
	.4byte EcruteakCity_House1
	.4byte EcruteakCity_House2
	.4byte EcruteakCity_DanceTheater
	.4byte EcruteakCity_TinTowerGate
	.4byte EcruteakCity_WiseTriosRoom

gMapGroup7::
	.4byte OlivineCity_PokemonCenter_1F
	.4byte OlivineCity_PokemonCenter_2F
	.4byte OlivineCity_Mart
	.4byte OlivineCity_Gym
	.4byte OlivineCity_House1
	.4byte OlivineCity_House2
	.4byte OlivineCity_House3
	.4byte OlivineCity_Cafe
	.4byte OlivineCity_PortPassage
	.4byte OlivineCity_Port

gMapGroup8::
	.4byte CianwoodCity_PokemonCenter_1F
	.4byte CianwoodCity_PokemonCenter_2F
	.4byte CianwoodCity_Gym
	.4byte CianwoodCity_House
	.4byte CianwoodCity_PhotoStudio
	.4byte CianwoodCity_Pharmacy
	.4byte CianwoodCity_ManiasHouse
	.4byte CianwoodCity_PokeSeersHouse

gMapGroup9::
	.4byte MahoganyTown_PokemonCenter_1F
	.4byte MahoganyTown_PokemonCenter_2F
	.4byte MahoganyTown_Gym
	.4byte MahoganyTown_House
	.4byte MahoganyTown_Shop

gMapGroup10::
	.4byte BlackthornCity_PokemonCenter_1F
	.4byte BlackthornCity_PokemonCenter_2F
	.4byte BlackthornCity_Mart
	.4byte BlackthornCity_Gym_1F
	.4byte BlackthornCity_Gym_2F
	.4byte BlackthornCity_House1
	.4byte BlackthornCity_House2
	.4byte BlackthornCity_MoveDeletersHouse

gMapGroup11::
	.4byte LakeOfRage_HiddenPowerHouse
	.4byte LakeOfRage_FishingGurusHouse

gMapGroup12::
	.4byte RuinsOfAlph_ResearchCenter

gMapGroup13::
	.4byte Route29_Gate

gMapGroup14::
	.4byte Route30_Berry_House
	.4byte Route30_Mr_Pokemons_House

gMapGroup15::
	.4byte Route31_Gate

gMapGroup16::
	.4byte Route32_Gate
	.4byte Route32_PokemonCenter_1F
	.4byte Route32_PokemonCenter_2F

gMapGroup17::
	.4byte Route34_Gate1
	.4byte Route34_Gate2
	.4byte Route34_PokemonDayCare

gMapGroup18::
	.4byte Route35_Gate
	.4byte Route35_National_Park_Gate

gMapGroup19::
	.4byte Route36_Gate
	.4byte Route36_National_Park_Gate

gMapGroup20::
	.4byte Route38_Gate

gMapGroup21::
	.4byte Route39_MooMooFarmHouse
	.4byte Route39_MooMooFarmBarn

gMapGroup22::
	.4byte Route40_BattleTower_Gate

gMapGroup23::
	.4byte Route42_Gate

gMapGroup24::
	.4byte Route43_Gate1
	.4byte Route43_Gate2

gMapGroup25::
	.4byte SilverCave_Exterior_PokemonCenter_1F
	.4byte SilverCave_Exterior_PokemonCenter_2F

gMapGroup26::
	.4byte DarkCave_Violet
	.4byte DarkCave_Blackthorn
	.4byte SproutTower_1F
	.4byte SproutTower_2F
	.4byte SproutTower_3F
	.4byte RuinsOfAlph_MainChamber
	.4byte RuinsOfAlph_KabutoPuzzleChamber
	.4byte RuinsOfAlph_KabutoItemRoom
	.4byte RuinsOfAlph_KabutoWordRoom
	.4byte RuinsOfAlph_AerodactylPuzzleChamber
	.4byte RuinsOfAlph_AerodactylItemRoom
	.4byte RuinsOfAlph_AerodactylWordRoom
	.4byte RuinsOfAlph_OmanytePuzzleChamber
	.4byte RuinsOfAlph_OmanyteItemRoom
	.4byte RuinsOfAlph_OmanyteWordRoom
	.4byte RuinsOfAlph_HoOhPuzzleChamber
	.4byte RuinsOfAlph_HoOhItemRoom
	.4byte RuinsOfAlph_HoOhWordRoom
	.4byte UnionCave_1F
	.4byte UnionCave_B1F
	.4byte UnionCave_B2F
	.4byte SlowpokeWell_B1F
	.4byte SlowpokeWell_B2F
	.4byte IlexForest
	.4byte RadioTower_1F
	.4byte RadioTower_2F
	.4byte RadioTower_3F
	.4byte RadioTower_4F
	.4byte RadioTower_5F
	.4byte NationalPark
	.4byte BurnedTower_1F
	.4byte BurnedTower_B1F
	.4byte TinTower_1F
	.4byte TinTower_2F
	.4byte TinTower_3F
	.4byte TinTower_4F
	.4byte TinTower_5F
	.4byte TinTower_6F
	.4byte TinTower_7F
	.4byte TinTower_8F
	.4byte TinTower_9F
	.4byte TinTower_Roof
	.4byte Lighthouse_1F
	.4byte Lighthouse_2F
	.4byte Lighthouse_3F
	.4byte Lighthouse_4F
	.4byte Lighthouse_5F
	.4byte Lighthouse_6F
	.4byte WhirlIslands_1F_NE
	.4byte WhirlIslands_1F_NW
	.4byte WhirlIslands_1F_SE
	.4byte WhirlIslands_1F_SW
	.4byte WhirlIslands_B1F
	.4byte WhirlIslands_B2F
	.4byte WhirlIslands_Cave
	.4byte WhirlIslands_LugiasChamber
	.4byte MtMortar_1F_Outer
	.4byte MtMortar_1F_Inner
	.4byte MtMortar_2F
	.4byte MtMortar_B1F
	.4byte TeamRocketBase_B1F
	.4byte TeamRocketBase_B2F
	.4byte TeamRocketBase_B3F
	.4byte IcePath_1F
	.4byte IcePath_B1F
	.4byte IcePath_B2F_Mahogany
	.4byte IcePath_B2F_Blackthorn
	.4byte IcePath_B3F
	.4byte DragonsDen_Entrance
	.4byte DragonsDen
	.4byte DragonsDen_DragonShrine
	.4byte FastShip_1F
	.4byte FastShip_B1F
	.4byte FastShip_Cabins_NNW_NNE_NE
	.4byte FastShip_Cabins_SE_SSE_Captains
	.4byte FastShip_Cabins_SW_SSW_NW
	.4byte SilverCave_Room1
	.4byte SilverCave_Room2
	.4byte SilverCave_Room3
	.4byte SilverCave_ItemRooms
	.4byte BattleTower_Exterior
	.4byte BattleTower_Lobby
	.4byte BattleTower_Elevator
	.4byte BattleTower_Hallway
	.4byte BattleTower_BattleRoom
	.4byte TohjoFalls
	.4byte VictoryRoad_Gate
	.4byte VictoryRoad

gMapGroup27::
	.4byte SecretBase_RedCave1
	.4byte SecretBase_BrownCave1
	.4byte SecretBase_BlueCave1
	.4byte SecretBase_YellowCave1
	.4byte SecretBase_Tree1
	.4byte SecretBase_Shrub1
	.4byte SecretBase_RedCave2
	.4byte SecretBase_BrownCave2
	.4byte SecretBase_BlueCave2
	.4byte SecretBase_YellowCave2
	.4byte SecretBase_Tree2
	.4byte SecretBase_Shrub2
	.4byte SecretBase_RedCave3
	.4byte SecretBase_BrownCave3
	.4byte SecretBase_BlueCave3
	.4byte SecretBase_YellowCave3
	.4byte SecretBase_Tree3
	.4byte SecretBase_Shrub3
	.4byte SecretBase_RedCave4
	.4byte SecretBase_BrownCave4
	.4byte SecretBase_BlueCave4
	.4byte SecretBase_YellowCave4
	.4byte SecretBase_Tree4
	.4byte SecretBase_Shrub4
	.4byte SingleBattleColosseum
	.4byte TradeCenter
	.4byte RecordCorner
	.4byte DoubleBattleColosseum
	.4byte LinkContestRoom1
	.4byte UnknownLinkContestRoom_25_29
	.4byte UnknownLinkContestRoom_25_30
	.4byte UnknownLinkContestRoom_25_31
	.4byte UnknownLinkContestRoom_25_32
	.4byte UnknownLinkContestRoom_25_33
	.4byte UnknownLinkContestRoom_25_34
	.4byte LinkContestRoom2
	.4byte LinkContestRoom3
	.4byte LinkContestRoom4
	.4byte LinkContestRoom5
	.4byte LinkContestRoom6
	.4byte BattlePyramidSquare01
	.4byte BattlePyramidSquare02
	.4byte BattlePyramidSquare03
	.4byte BattlePyramidSquare04
	.4byte BattlePyramidSquare05
	.4byte BattlePyramidSquare06
	.4byte BattlePyramidSquare07
	.4byte BattlePyramidSquare08
	.4byte BattlePyramidSquare09
	.4byte BattlePyramidSquare10
	.4byte BattlePyramidSquare11
	.4byte BattlePyramidSquare12
	.4byte BattlePyramidSquare13
	.4byte BattlePyramidSquare14
	.4byte BattlePyramidSquare15
	.4byte BattlePyramidSquare16
	.4byte UnionRoom

gMapGroup28::
	.4byte BattleFrontier_OutsideWest
	.4byte BattleFrontier_BattleTowerLobby
	.4byte BattleFrontier_BattleTowerElevator
	.4byte BattleFrontier_BattleTowerCorridor
	.4byte BattleFrontier_BattleTowerBattleRoom
	.4byte SouthernIsland_Exterior
	.4byte SouthernIsland_Interior
	.4byte BattleFrontier_OutsideEast
	.4byte BattleFrontier_BattleTowerMultiBattleRoom
	.4byte BattleFrontier_BattleTowerCorridor2
	.4byte BattleFrontier_BattleTowerBattleRoom2
	.4byte BattleFrontier_BattleDomeLobby
	.4byte BattleFrontier_BattleDomeCorridor
	.4byte BattleFrontier_BattleDomePreBattleRoom
	.4byte BattleFrontier_BattleDomeBattleRoom
	.4byte BattleFrontier_BattlePalaceLobby
	.4byte BattleFrontier_BattlePalaceCorridor
	.4byte BattleFrontier_BattlePalaceBattleRoom
	.4byte BattleFrontier_BattlePyramidLobby
	.4byte BattleFrontier_BattlePyramidEmptySquare
	.4byte BattleFrontier_BattlePyramidTop
	.4byte BattleFrontier_BattleArenaLobby
	.4byte BattleFrontier_BattleArenaCorridor
	.4byte BattleFrontier_BattleArenaBattleRoom
	.4byte BattleFrontier_BattleFactoryLobby
	.4byte BattleFrontier_BattleFactoryPreBattleRoom
	.4byte BattleFrontier_BattleFactoryBattleRoom
	.4byte BattleFrontier_BattlePikeLobby
	.4byte BattleFrontier_BattlePikeCorridor
	.4byte BattleFrontier_BattlePikeThreePathRoom
	.4byte BattleFrontier_BattlePikeRandomRoom1
	.4byte BattleFrontier_BattlePikeRandomRoom2
	.4byte BattleFrontier_BattlePikeRandomRoom3
	.4byte BattleFrontier_RankingHall
	.4byte BattleFrontier_Lounge1
	.4byte BattleFrontier_BattlePointExchangeServiceCorner
	.4byte BattleFrontier_Lounge2
	.4byte BattleFrontier_Lounge3
	.4byte BattleFrontier_Lounge4
	.4byte BattleFrontier_ScottsHouse
	.4byte BattleFrontier_Lounge5
	.4byte BattleFrontier_Lounge6
	.4byte BattleFrontier_Lounge7
	.4byte BattleFrontier_ReceptionGate
	.4byte BattleFrontier_Lounge8
	.4byte BattleFrontier_Lounge9
	.4byte BattleFrontier_PokemonCenter_1F
	.4byte BattleFrontier_PokemonCenter_2F
	.4byte BattleFrontier_Mart
	.4byte FarawayIsland_Entrance
	.4byte FarawayIsland_Interior
	.4byte BirthIsland_Exterior
	.4byte BirthIsland_Harbor
	.4byte TrainerHill_Entrance
	.4byte TrainerHill_1F
	.4byte TrainerHill_2F
	.4byte TrainerHill_3F
	.4byte TrainerHill_4F
	.4byte TrainerHill_Roof
	.4byte NavelRock_Exterior
	.4byte NavelRock_Harbor
	.4byte NavelRock_Entrance
	.4byte NavelRock_B1F
	.4byte NavelRock_Fork
	.4byte NavelRock_Up1
	.4byte NavelRock_Up2
	.4byte NavelRock_Up3
	.4byte NavelRock_Up4
	.4byte NavelRock_Top
	.4byte NavelRock_Down01
	.4byte NavelRock_Down02
	.4byte NavelRock_Down03
	.4byte NavelRock_Down04
	.4byte NavelRock_Down05
	.4byte NavelRock_Down06
	.4byte NavelRock_Down07
	.4byte NavelRock_Down08
	.4byte NavelRock_Down09
	.4byte NavelRock_Down10
	.4byte NavelRock_Down11
	.4byte NavelRock_Bottom
	.4byte TrainerHill_Elevator

gMapGroup29::
	.4byte Route27_House

gMapGroup30::
	.4byte Route26_House1
	.4byte Route26_House2

gMapGroup31::
	.4byte IndigoPlateau_PokemonCenter_1F
	.4byte IndigoPlateau_PokemonCenter_2F
	.4byte IndigoPlateau_WillsRoom
	.4byte IndigoPlateau_KogasRoom
	.4byte IndigoPlateau_BrunosRoom
	.4byte IndigoPlateau_KarensRoom
	.4byte IndigoPlateau_LancesRoom
	.4byte IndigoPlateau_HallOfFame

gMapGroup32::
	.4byte Route28_House

gMapGroup33::
	.4byte PalletTown_RedsHouse_1F
	.4byte PalletTown_RedsHouse_2F
	.4byte PalletTown_BluesHouse
	.4byte PalletTown_ProfOaksLab

gMapGroup34::
	.4byte PacifidlogTown_PokemonCenter_1F
	.4byte PacifidlogTown_PokemonCenter_2F
	.4byte ViridianCity_TrainerHouse_1F

gMapGroup35::
	.4byte VerdanturfTown_BattleTentLobby
	.4byte VerdanturfTown_BattleTentCorridor
	.4byte VerdanturfTown_BattleTentBattleRoom
	.4byte FallarborTown_BattleTentLobby
	.4byte FallarborTown_BattleTentCorridor
	.4byte FallarborTown_BattleTentBattleRoom
	.4byte LavaridgeTown_PokemonCenter_1F
	.4byte LavaridgeTown_PokemonCenter_2F
	.4byte LilycoveCity_ContestLobby
	.4byte LilycoveCity_ContestHall
	.4byte LilycoveCity_PokemonCenter_1F
	.4byte LilycoveCity_PokemonCenter_2F
	.4byte MossdeepCity_PokemonCenter_1F
	.4byte MossdeepCity_PokemonCenter_2F
	.4byte SootopolisCity_PokemonCenter_1F
	.4byte SootopolisCity_PokemonCenter_2F
	.4byte EverGrandeCity_PokemonCenter_1F
	.4byte EverGrandeCity_PokemonCenter_2F
	.4byte SlateportCity_BattleTentLobby
	.4byte SlateportCity_BattleTentCorridor
	.4byte SlateportCity_BattleTentBattleRoom
	.4byte ArtisanCave_B1F
	.4byte ArtisanCave_1F

	.align 2
gMapGroups::
	.4byte gMapGroup0
	.4byte gMapGroup1
	.4byte gMapGroup2
	.4byte gMapGroup3
	.4byte gMapGroup4
	.4byte gMapGroup5
	.4byte gMapGroup6
	.4byte gMapGroup7
	.4byte gMapGroup8
	.4byte gMapGroup9
	.4byte gMapGroup10
	.4byte gMapGroup11
	.4byte gMapGroup12
	.4byte gMapGroup13
	.4byte gMapGroup14
	.4byte gMapGroup15
	.4byte gMapGroup16
	.4byte gMapGroup17
	.4byte gMapGroup18
	.4byte gMapGroup19
	.4byte gMapGroup20
	.4byte gMapGroup21
	.4byte gMapGroup22
	.4byte gMapGroup23
	.4byte gMapGroup24
	.4byte gMapGroup25
	.4byte gMapGroup26
	.4byte gMapGroup27
	.4byte gMapGroup28
	.4byte gMapGroup29
	.4byte gMapGroup30
	.4byte gMapGroup31
	.4byte gMapGroup32
	.4byte gMapGroup33
	.4byte gMapGroup34
	.4byte gMapGroup35

