BattlePyramidSquare01_EventObjects:
	object_event 1, EVENT_OBJ_GFX_ZNINJA_BOY, 0, 2, 3, 4, MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT, 1, 1, 1, 3, BattlePyramid_TrainerBattle, 0
	object_event 2, EVENT_OBJ_GFX_ZGIRL_3, 0, 5, 3, 4, MOVEMENT_TYPE_FACE_DOWN_AND_LEFT, 1, 1, 1, 3, BattlePyramid_TrainerBattle, 0
	object_event 3, EVENT_OBJ_GFX_ZRICH_BOY, 0, 2, 6, 4, MOVEMENT_TYPE_FACE_UP_AND_RIGHT, 1, 1, 1, 5, BattlePyramid_TrainerBattle, 0
	object_event 4, EVENT_OBJ_GFX_ZBOY_2, 0, 6, 6, 4, MOVEMENT_TYPE_FACE_LEFT, 1, 1, 1, 4, BattlePyramid_TrainerBattle, 0
	object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 4, 1, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattlePyramid_FindItemBall, 0
	object_event 6, EVENT_OBJ_GFX_ITEM_BALL, 0, 7, 4, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattlePyramid_FindItemBall, 0
	object_event 7, EVENT_OBJ_GFX_ITEM_BALL, 0, 0, 4, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattlePyramid_FindItemBall, 0

BattlePyramidSquare01_MapEvents::
	map_events BattlePyramidSquare01_EventObjects, 0x0, 0x0, 0x0

