PalletTown_RedsHouse_1F:
	.4byte PalletTown_RedsHouse_1F_Layout
	.4byte PalletTown_RedsHouse_1F_MapEvents
	.4byte PalletTown_RedsHouse_1F_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_PALLET_TOWN_REDS_HOUSE_1F
	.byte MAPSEC_PALLET_TOWN
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

