EcruteakCity_House2_EventObjects:
	object_event 1, EVENT_OBJ_GFX_COOLTRAINER_M, 0, 2, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, MauvilleCity_House2_EventScript_210C5D, 0
	object_event 2, EVENT_OBJ_GFX_BOOK, 0, 3, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, MauvilleCity_House2_EventScript_210C5D, 0

EcruteakCity_House2_MapWarps:
	warp_def 3, 7, 0, 10, MAP_ECRUTEAK_CITY
	warp_def 4, 7, 0, 10, MAP_ECRUTEAK_CITY

EcruteakCity_House2_MapEvents::
	map_events EcruteakCity_House2_EventObjects, EcruteakCity_House2_MapWarps, 0x0, 0x0

