CherrygroveCity_Guide_Gents_House_EventObjects::
	object_event 1, EVENT_OBJ_GFX_OLD_MAN, 0, 2, 3, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, FALSE, 0, NULL, 0

CherrygroveCity_Guide_Gents_House_MapWarps::
	warp_def 2, 7, 0, 1, MAP_CHERRYGROVE_CITY
	warp_def 3, 7, 0, 1, MAP_CHERRYGROVE_CITY

CherrygroveCity_Guide_Gents_House_MapEvents::
	map_events CherrygroveCity_Guide_Gents_House_EventObjects, CherrygroveCity_Guide_Gents_House_MapWarps, 0x0, 0x0
