OlivineCity_House3_EventObjects::
	object_event 1, EVENT_OBJ_GFX_POKEFAN_M, 0, 1, 2, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, RustboroCity_House3_EventScript_216191, 0
	object_event 2, EVENT_OBJ_GFX_LASS, 0, 5, 5, 3, MOVEMENT_TYPE_WANDER_LEFT_AND_RIGHT, 2, 0, 0, 0, RustboroCity_House3_EventScript_21619A, 0

OlivineCity_House3_MapWarps::
	warp_def 2, 7, 0, 4, MAP_OLIVINE_CITY
	warp_def 3, 7, 0, 4, MAP_OLIVINE_CITY

OlivineCity_House3_MapEvents::
	map_events OlivineCity_House3_EventObjects, OlivineCity_House3_MapWarps, 0x0, 0x0
