IndigoPlateau_KarensRoom:
	.4byte IndigoPlateau_KarensRoom_Layout
	.4byte IndigoPlateau_KarensRoom_MapEvents
	.4byte IndigoPlateau_KarensRoom_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_INDIGO_PLATEAU_KARENS_ROOM
	.byte MAPSEC_INDIGO_PLATEAU
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

