CianwoodCity_ManiasHouse_EventObjects::
	object_event 1, EVENT_OBJ_GFX_GUITARIST, 0, 2, 4, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, PetalburgCity_WallysHouse_EventScript_204278, 0

CianwoodCity_ManiasHouse_MapWarps::
	warp_def 2, 7, 0, 0, MAP_CIANWOOD_CITY
	warp_def 3, 7, 0, 0, MAP_CIANWOOD_CITY

CianwoodCity_ManiasHouse_MapEvents::
	map_events CianwoodCity_ManiasHouse_EventObjects, CianwoodCity_ManiasHouse_MapWarps, 0x0, 0x0
