IcePath_B2F_Mahogany:
	.4byte IcePath_B2F_Mahogany_Layout
	.4byte IcePath_B2F_Mahogany_MapEvents
	.4byte IcePath_B2F_Mahogany_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_ICE_PATH_B2F_MAHOGANY
	.byte MAPSEC_ICE_PATH
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_UNDERGROUND
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=1, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

