GoldenrodCity_House1_EventObjects::
	object_event 1, EVENT_OBJ_GFX_FAT_MAN, PAL_NPC_GREEN, 2, 4, 3, MOVEMENT_TYPE_WANDER_UP_AND_DOWN, 0, 0, 0, 0, SlateportCity_Mart_EventScript_20DC49, 0
	object_event 2, EVENT_OBJ_GFX_LASS, 0, 5, 3, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, 0, 0, SlateportCity_Mart_EventScript_20DC76, 0

GoldenrodCity_House1_MapWarps::
	warp_def 2, 7, 0, 6, MAP_GOLDENROD_CITY
	warp_def 3, 7, 0, 6, MAP_GOLDENROD_CITY

GoldenrodCity_House1_MapEvents::
	map_events GoldenrodCity_House1_EventObjects, GoldenrodCity_House1_MapWarps, 0x0, 0x0
