IcePath_B2F_Blackthorn:
	.4byte IcePath_B2F_Blackthorn_Layout
	.4byte IcePath_B2F_Blackthorn_MapEvents
	.4byte IcePath_B2F_Blackthorn_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_ICE_PATH_B2F_BLACKTHORN
	.byte MAPSEC_ICE_PATH
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_UNDERGROUND
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=1, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

