DragonsDen_DragonShrine:
	.4byte DragonsDen_DragonShrine_Layout
	.4byte DragonsDen_DragonShrine_MapEvents
	.4byte DragonsDen_DragonShrine_MapScripts
	.4byte 0x0
	.2byte MUS_AJITO
	.2byte LAYOUT_DRAGONS_DEN_DRAGON_SHRINE
	.byte MAPSEC_DRAGONS_DEN
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_AQUA

