DarkCave_Blackthorn:
	.4byte DarkCave_Blackthorn_Layout
	.4byte DarkCave_Blackthorn_MapEvents
	.4byte DarkCave_Blackthorn_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_DARK_CAVE_BLACKTHORN
	.byte MAPSEC_DARK_CAVE
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_UNDERGROUND
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=1, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

