LakeOfRage_HiddenPowerHouse_EventObjects::
	object_event 1, EVENT_OBJ_GFX_FAT_MAN, 0, 2, 3, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, VerdanturfTown_FriendshipRatersHouse_EventScript_203031, 0

LakeOfRage_HiddenPowerHouse_MapWarps::
	warp_def 2, 7, 0, 0, MAP_LAKE_OF_RAGE
	warp_def 3, 7, 0, 0, MAP_LAKE_OF_RAGE

LakeOfRage_HiddenPowerHouse_MapEvents::
	map_events LakeOfRage_HiddenPowerHouse_EventObjects, LakeOfRage_HiddenPowerHouse_MapWarps, 0x0, 0x0
