LakeOfRage_FishingGurusHouse_EventObjects::
	object_event 1, EVENT_OBJ_GFX_FISHING_GURU, 0, 2, 3, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, VerdanturfTown_Mart_EventScript_202587, 0

LakeOfRage_FishingGurusHouse_MapWarps::
	warp_def 2, 7, 0, 1, MAP_LAKE_OF_RAGE
	warp_def 3, 7, 0, 1, MAP_LAKE_OF_RAGE

LakeOfRage_FishingGurusHouse_MapEvents::
	map_events LakeOfRage_FishingGurusHouse_EventObjects, LakeOfRage_FishingGurusHouse_MapWarps, 0x0, 0x0
