PalletTown_RedsHouse_2F::
	.4byte PalletTown_RedsHouse_2F_Layout
	.4byte PalletTown_RedsHouse_2F_MapEvents
	.4byte PalletTown_RedsHouse_2F_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte 2776
	.byte MAPSEC_PALLET_TOWN
	.byte FALSE
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_INDOOR
	.2byte PAL_INDOOR
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
