BattlePyramidSquare12_EventObjects:
	object_event 1, EVENT_OBJ_GFX_ZWOMAN_1, 0, 7, 5, 4, MOVEMENT_TYPE_FACE_LEFT, 1, 1, 1, 7, BattlePyramid_TrainerBattle, 0
	object_event 2, EVENT_OBJ_GFX_ZWOMAN_1, 0, 0, 5, 4, MOVEMENT_TYPE_FACE_RIGHT, 1, 1, 1, 7, BattlePyramid_TrainerBattle, 0
	object_event 3, EVENT_OBJ_GFX_ZWOMAN_1, 0, 3, 0, 4, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 1, 6, BattlePyramid_TrainerBattle, 0
	object_event 4, EVENT_OBJ_GFX_ZWOMAN_1, 0, 3, 3, 4, MOVEMENT_TYPE_FACE_UP, 1, 1, 1, 3, BattlePyramid_TrainerBattle, 0
	object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 7, 2, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattlePyramid_FindItemBall, 0
	object_event 6, EVENT_OBJ_GFX_ITEM_BALL, 0, 0, 3, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattlePyramid_FindItemBall, 0
	object_event 7, EVENT_OBJ_GFX_ITEM_BALL, 0, 7, 7, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattlePyramid_FindItemBall, 0

BattlePyramidSquare12_MapEvents::
	map_events BattlePyramidSquare12_EventObjects, 0x0, 0x0, 0x0

