BlackthornCity_MoveDeletersHouse_EventObjects:
	object_event 1, EVENT_OBJ_GFX_SUPER_NERD, 0, 2, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, FortreeCity_House3_EventScript_217AE8, 0

BlackthornCity_MoveDeletersHouse_MapWarps:
	warp_def 2, 7, 0, 5, MAP_BLACKTHORN_CITY
	warp_def 3, 7, 0, 5, MAP_BLACKTHORN_CITY

BlackthornCity_MoveDeletersHouse_MapEvents::
	map_events BlackthornCity_MoveDeletersHouse_EventObjects, BlackthornCity_MoveDeletersHouse_MapWarps, 0x0, 0x0

