BlackthornCity_MoveDeletersHouse::
	.4byte House1_Layout
	.4byte BlackthornCity_MoveDeletersHouse_MapEvents
	.4byte BlackthornCity_MoveDeletersHouse_MapScripts
	.4byte 0x0
	.2byte MUS_MACHI_S3
	.2byte 59
	.byte MAPSEC_BLACKTHORN_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte PAL_INDOOR
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
