RuinsOfAlph_MainChamber:
	.4byte RuinsOfAlph_MainChamber_Layout
	.4byte RuinsOfAlph_MainChamber_MapEvents
	.4byte RuinsOfAlph_MainChamber_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_RUINS_OF_ALPH_MAIN_CHAMBER
	.byte MAPSEC_RUINS_OF_ALPH
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_UNDERGROUND
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=1, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

