RuinsOfAlph_MainChamber::
	.4byte RuinsOfAlph_MainChamber_Layout
	.4byte RuinsOfAlph_MainChamber_MapEvents
	.4byte RuinsOfAlph_MainChamber_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte 2699
	.byte MAPSEC_RUINS_OF_ALPH
	.byte FALSE
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_UNDERGROUND
	.2byte 1
	map_header_flags allow_bike=0, allow_escape_rope=1, allow_run=0, show_map_name=TRUE
	.byte MAP_BATTLE_SCENE_NORMAL
