CianwoodCity_PhotoStudio_EventObjects::
	object_event 1, EVENT_OBJ_GFX_FISHING_GURU, PAL_NPC_RED, 2, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, LavaridgeTown_House_EventScript_1FF912, 0

CianwoodCity_PhotoStudio_MapWarps::
	warp_def 2, 7, 0, 4, MAP_CIANWOOD_CITY
	warp_def 3, 7, 0, 4, MAP_CIANWOOD_CITY

CianwoodCity_PhotoStudio_MapEvents::
	map_events CianwoodCity_PhotoStudio_EventObjects, CianwoodCity_PhotoStudio_MapWarps, 0x0, 0x0
