NewBarkTown_ProfElmsLab::
	.4byte NewBarkTown_ProfElmsLab_Layout
	.4byte NewBarkTown_ProfElmsLab_MapEvents
	.4byte NewBarkTown_ProfElmsLab_MapScripts
	.4byte 0x0
	.2byte MUS_ODAMAKI
	.2byte 58
	.byte MAPSEC_NEW_BARK_TOWN
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte PAL_INDOOR
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
