GoldenrodCity_UndergroundWarehouse:
	.4byte GoldenrodCity_UndergroundWarehouse_Layout
	.4byte GoldenrodCity_UndergroundWarehouse_MapEvents
	.4byte GoldenrodCity_UndergroundWarehouse_MapScripts
	.4byte 0x0
	.2byte MUS_FUNE_KAN
	.2byte LAYOUT_GOLDENROD_CITY_UNDERGROUND_WAREHOUSE
	.byte MAPSEC_GOLDENROD_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

