GoldenrodCity_UndergroundWarehouse::
	.4byte GoldenrodCity_UndergroundWarehouse_Layout
	.4byte GoldenrodCity_UndergroundWarehouse_MapEvents
	.4byte GoldenrodCity_UndergroundWarehouse_MapScripts
	.4byte 0x0
	.2byte MUS_FUNE_KAN
	.2byte 87
	.byte MAPSEC_GOLDENROD_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte PAL_DUNGEON_DAY
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
