Route35_National_Park_Gate::
	.4byte Route35_National_Park_Gate_Layout
	.4byte Route35_National_Park_Gate_MapEvents
	.4byte Route35_National_Park_Gate_MapScripts
	.4byte 0x0
	.2byte MUS_NIBI
	.2byte 445
	.byte MAPSEC_ROUTE_35
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
