OlivineCity_House1_EventObjects::
	object_event 1, EVENT_OBJ_GFX_FISHING_GURU, PAL_NPC_GREEN, 2, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, RustboroCity_House1_EventScript_21593F, 0

OlivineCity_House1_MapWarps::
	warp_def 2, 7, 0, 5, MAP_OLIVINE_CITY
	warp_def 3, 7, 0, 5, MAP_OLIVINE_CITY

OlivineCity_House1_MapEvents::
	map_events OlivineCity_House1_EventObjects, OlivineCity_House1_MapWarps, 0x0, 0x0
