RuinsOfAlph_Exterior:
	.4byte RuinsOfAlph_Exterior_Layout
	.4byte RuinsOfAlph_Exterior_MapEvents
	.4byte RuinsOfAlph_Exterior_MapScripts
	.4byte RuinsOfAlph_Exterior_MapConnections
	.2byte MUS_DOORO_X3
	.2byte LAYOUT_RUINS_OF_ALPH_EXTERIOR
	.byte MAPSEC_RUINS_OF_ALPH
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_6
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

