GoldenrodCity_UndergroundSwitchRoomEntrances::
	.4byte GoldenrodCity_UndergroundSwitchRoomEntrances_Layout
	.4byte GoldenrodCity_UndergroundSwitchRoomEntrances_MapEvents
	.4byte GoldenrodCity_UndergroundSwitchRoomEntrances_MapScripts
	.4byte 0x0
	.2byte MUS_FINECITY
	.2byte 85
	.byte MAPSEC_GOLDENROD_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
