	.align 2
gTilesetPalettes_GeneralNite::
	.incbin "data/tilesets/primary/general/palettes/nite/00.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/01.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/02.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/03.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/04.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/05.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/06.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/07.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/08.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/09.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/10.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/11.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/12.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/13.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/14.gbapal"
	.incbin "data/tilesets/primary/general/palettes/nite/15.gbapal"
	
	.align 2
gTilesetPalettes_GeneralMorn::
	.incbin "data/tilesets/primary/general/palettes/morn/00.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/01.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/02.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/03.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/04.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/05.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/06.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/07.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/08.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/09.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/10.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/11.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/12.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/13.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/14.gbapal"
	.incbin "data/tilesets/primary/general/palettes/morn/15.gbapal"

	.align 2
gTilesetTiles_Petalburg:: @ 8339E08
	.incbin "data/tilesets/secondary/petalburg/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Petalburg:: @ 833A704
	.incbin "data/tilesets/secondary/petalburg/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideWest:: @ 834C8B4
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideWest:: @ 834E3E4
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideEast:: @ 834E5E4
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideEast:: @ 834F984
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideBuilding:: @ 834FB84
	.incbin "data/tilesets/primary/building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideBuilding:: @ 83508BC
	.incbin "data/tilesets/primary/building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/15.gbapal"

	.align 2
gTilesetPalettes_InsideBuilding_DungeonDay:: @ 83508BC
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_day/15.gbapal"

	.align 2
gTilesetPalettes_InsideBuilding_DungeonDark:: @ 83508BC
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/dungeon_dark/15.gbapal"

	.align 2
gTilesetPalettes_InsideBuilding_Nite:: @ 83508BC
	.incbin "data/tilesets/primary/building/palettes/nite/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/nite/15.gbapal"

	.align 2
gTilesetTiles_BikeShop:: @ 8363090
	.incbin "data/tilesets/secondary/bike_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BikeShop:: @ 83643C0
	.incbin "data/tilesets/secondary/bike_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/brown_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBrownCave:: @ 8365788
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/tree/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseTree:: @ 8365EAC
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/shrub/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseShrub:: @ 8366614
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/blue_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBlueCave:: @ 8366C30
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseYellowCave:: @ 8367368
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/red_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseRedCave:: @ 83679A0
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBaseBrownCave:: @ 8367BA0
	.incbin "data/tilesets/secondary/secret_base/brown_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseTree:: @ 8368600
	.incbin "data/tilesets/secondary/secret_base/tree/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseShrub:: @ 8369060
	.incbin "data/tilesets/secondary/secret_base/shrub/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseBlueCave:: @ 8369AC0
	.incbin "data/tilesets/secondary/secret_base/blue_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseYellowCave:: @ 836A520
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseRedCave:: @ 836AF80
	.incbin "data/tilesets/secondary/secret_base/red_cave/tiles.4bpp"

	.align 2
gTilesetTiles_GenericBuilding:: @ 8371998
	.incbin "data/tilesets/secondary/generic_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GenericBuilding:: @ 83733C4
	.incbin "data/tilesets/secondary/generic_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBase:: @ 837AA48
	.incbin "data/tilesets/primary/secret_base/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/primary/secret_base/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_SecretBase:: @ 8382A48
	.incbin "data/tilesets/primary/secret_base/palettes/00.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/01.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/02.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/03.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/04.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/05.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/06.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/07.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/08.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/09.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/10.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/11.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/12.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/13.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/14.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontier:: @ 8383EC4
	.incbin "data/tilesets/secondary/battle_frontier/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontier:: @ 8384BC8
	.incbin "data/tilesets/secondary/battle_frontier/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePalace:: @ 8384DC8
	.incbin "data/tilesets/secondary/battle_palace/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePalace:: @ 8385540
	.incbin "data/tilesets/secondary/battle_palace/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleDome:: @ 8385740
	.incbin "data/tilesets/secondary/battle_dome/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleDome:: @ 8386990
	.incbin "data/tilesets/secondary/battle_dome/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFactory:: @ 8386B90
	.incbin "data/tilesets/secondary/battle_factory/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFactory:: @ 8387D7C
	.incbin "data/tilesets/secondary/battle_factory/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePike:: @ 8387F7C
	.incbin "data/tilesets/secondary/battle_pike/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePike:: @ 8389250
	.incbin "data/tilesets/secondary/battle_pike/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleArena:: @ 8389450
	.incbin "data/tilesets/secondary/battle_arena/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleArena:: @ 8389F8C
	.incbin "data/tilesets/secondary/battle_arena/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePyramid:: @ 838A18C
	.incbin "data/tilesets/secondary/battle_pyramid/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePyramid:: @ 838B39C
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrainerHill:: @ 838F3D4
	.incbin "data/tilesets/secondary/trainer_hill/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrainerHill:: @ 83904C4
	.incbin "data/tilesets/secondary/trainer_hill/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierRankingHall:: @ 8392458
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierRankingHall:: @ 8392CAC
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleTent:: @ 8392EAC
	.incbin "data/tilesets/secondary/battle_tent/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleTent:: @ 8393910
	.incbin "data/tilesets/secondary/battle_tent/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/15.gbapal"

	.align 2
gTilesetPalettes_UnionRoom:: @ 8395678
	.incbin "data/tilesets/secondary/union_room/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnionRoom:: @ 8395878
	.incbin "data/tilesets/secondary/union_room/tiles.4bpp.lz"
	
	.align 2
gTilesetTiles_Building2:: @ 834FB84
	.incbin "data/tilesets/primary/building2/tiles.4bpp.lz"
	
	.align 2
gTilesetPalettes_Building2:: @ 83508BC
	.incbin "data/tilesets/primary/building2/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building2/palettes/15.gbapal"

	.align 2
gTilesetTiles_Special:: @ 834FB84
	.incbin "data/tilesets/primary/special/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Special:: @ 83508BC
	.incbin "data/tilesets/primary/special/palettes/00.gbapal"
	.incbin "data/tilesets/primary/special/palettes/01.gbapal"
	.incbin "data/tilesets/primary/special/palettes/02.gbapal"
	.incbin "data/tilesets/primary/special/palettes/03.gbapal"
	.incbin "data/tilesets/primary/special/palettes/04.gbapal"
	.incbin "data/tilesets/primary/special/palettes/05.gbapal"
	.incbin "data/tilesets/primary/special/palettes/06.gbapal"
	.incbin "data/tilesets/primary/special/palettes/07.gbapal"
	.incbin "data/tilesets/primary/special/palettes/08.gbapal"
	.incbin "data/tilesets/primary/special/palettes/09.gbapal"
	.incbin "data/tilesets/primary/special/palettes/10.gbapal"
	.incbin "data/tilesets/primary/special/palettes/11.gbapal"
	.incbin "data/tilesets/primary/special/palettes/12.gbapal"
	.incbin "data/tilesets/primary/special/palettes/13.gbapal"
	.incbin "data/tilesets/primary/special/palettes/14.gbapal"
	.incbin "data/tilesets/primary/special/palettes/15.gbapal"

    .align 2
gTilesetTiles_Contest:: @ 836BE3C
    .incbin "data/tilesets/secondary/contest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Contest:: @ 836C990
	.incbin "data/tilesets/secondary/contest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/15.gbapal"
