	.align 1
gMetatiles_General:: @ 83960F0
	.incbin "data/tilesets/primary/general/metatiles.bin"

	.align 1
gMetatileAttributes_General:: @ 83980F0
	.incbin "data/tilesets/primary/general/metatile_attributes.bin"

	.align 1
gMetatiles_Petalburg:: @ 83984F0
	.incbin "data/tilesets/secondary/petalburg/metatiles.bin"

	.align 1
gMetatileAttributes_Petalburg:: @ 8398DF0
	.incbin "data/tilesets/secondary/petalburg/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideWest:: @ 83AB3C6
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideWest:: @ 83AD3A6
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideEast:: @ 83AD7A2
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideEast:: @ 83AF782
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_attributes.bin"

	.align 1
gMetatiles_InsideBuilding:: @ 83AFB7E
	.incbin "data/tilesets/primary/building/metatiles.bin"

	.align 1
gMetatileAttributes_InsideBuilding:: @ 83AFBFE
	.incbin "data/tilesets/primary/building/metatile_attributes.bin"

	.align 1
gMetatiles_BikeShop:: @ 83BA0CC
	.incbin "data/tilesets/secondary/bike_shop/metatiles.bin"

	.align 1
gMetatileAttributes_BikeShop:: @ 83BB04C
	.incbin "data/tilesets/secondary/bike_shop/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBaseSecondary:: @ 83BB812
	.incbin "data/tilesets/secondary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBaseSecondary:: @ 83BCC52
	.incbin "data/tilesets/secondary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_Contest:: @ 83BD186
	.incbin "data/tilesets/secondary/contest/metatiles.bin"

	.align 1
gMetatileAttributes_Contest:: @ 83BE016
	.incbin "data/tilesets/secondary/contest/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding:: @ 83C1572
	.incbin "data/tilesets/secondary/generic_building/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding:: @ 83C3572
	.incbin "data/tilesets/secondary/generic_building/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBasePrimary:: @ 83C9EC4
	.incbin "data/tilesets/primary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBasePrimary:: @ 83C9EE4
	.incbin "data/tilesets/primary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontier:: @ 83CB640
	.incbin "data/tilesets/secondary/battle_frontier/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontier:: @ 83CD610
	.incbin "data/tilesets/secondary/battle_frontier/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePalace:: @ 83CDA0A
	.incbin "data/tilesets/secondary/battle_palace/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePalace:: @ 83CE4EA
	.incbin "data/tilesets/secondary/battle_palace/metatile_attributes.bin"

	.align 1
gMetatiles_BattleDome:: @ 83CE646
	.incbin "data/tilesets/secondary/battle_dome/metatiles.bin"

	.align 1
gMetatileAttributes_BattleDome:: @ 83D00F6
	.incbin "data/tilesets/secondary/battle_dome/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFactory:: @ 83D044C
	.incbin "data/tilesets/secondary/battle_factory/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFactory:: @ 83D1A6C
	.incbin "data/tilesets/secondary/battle_factory/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePike:: @ 83D1D30
	.incbin "data/tilesets/secondary/battle_pike/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePike:: @ 83D32E0
	.incbin "data/tilesets/secondary/battle_pike/metatile_attributes.bin"

	.align 1
gMetatiles_BattleArena:: @ 83D3596
	.incbin "data/tilesets/secondary/battle_arena/metatiles.bin"

	.align 1
gMetatileAttributes_BattleArena:: @ 83D40A6
	.incbin "data/tilesets/secondary/battle_arena/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePyramid:: @ 83D4208
	.incbin "data/tilesets/secondary/battle_pyramid/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePyramid:: @ 83D4FD8
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_attributes.bin"

	.align 1
gMetatiles_TrainerHill:: @ 83D9374
	.incbin "data/tilesets/secondary/trainer_hill/metatiles.bin"

	.align 1
gMetatileAttributes_TrainerHill:: @ 83DB1D4
	.incbin "data/tilesets/secondary/trainer_hill/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierRankingHall:: @ 83DD556
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierRankingHall:: @ 83DDB36
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_attributes.bin"

	.align 1
gMetatiles_BattleTent:: @ 83DDBF2
	.incbin "data/tilesets/secondary/battle_tent/metatiles.bin"

	.align 1
gMetatileAttributes_BattleTent:: @ 83DECC2
	.incbin "data/tilesets/secondary/battle_tent/metatile_attributes.bin"

	.align 1
gMetatiles_UnionRoom:: @ 83DF392
	.incbin "data/tilesets/secondary/union_room/metatiles.bin"

	.align 1
gMetatileAttributes_UnionRoom:: @ 83DF6A2
	.incbin "data/tilesets/secondary/union_room/metatile_attributes.bin"
	
	.align 1
gMetatiles_Building2:: @ 83960F0
	.incbin "data/tilesets/primary/building2/metatiles.bin"

	.align 1
gMetatileAttributes_Building2:: @ 83980F0
	.incbin "data/tilesets/primary/building2/metatile_attributes.bin"

	.align 1
gMetatiles_Special:: @ 83960F0
	.incbin "data/tilesets/primary/special/metatiles.bin"
	.align 1
gMetatileAttributes_Special:: @ 83960F0
	.incbin "data/tilesets/primary/special/metatile_attributes.bin"