GoldenrodCity_DepartmentStore_2F::
	.4byte GoldenrodCity_DepartmentStore_2F_Layout
	.4byte GoldenrodCity_DepartmentStore_2F_MapEvents
	.4byte GoldenrodCity_DepartmentStore_2F_MapScripts
	.4byte 0x0
	.2byte MUS_FRIENDLY
	.2byte 258
	.byte MAPSEC_GOLDENROD_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte PAL_INDOOR
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=FALSE
	.byte MAP_BATTLE_SCENE_NORMAL
