RuinsOfAlph_ResearchCenter:
	.4byte RuinsOfAlph_ResearchCenter_Layout
	.4byte RuinsOfAlph_ResearchCenter_MapEvents
	.4byte RuinsOfAlph_ResearchCenter_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_RUINS_OF_ALPH_RESEARCH_CENTER
	.byte MAPSEC_RUINS_OF_ALPH
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

