TinTower_9F_EventObjects::
	object_event 1, EVENT_OBJ_GFX_ITEM_BALL, 0, 9, 1, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, SeafloorCavern_Room8_EventScript_2908BA, FLAG_TEMP_1C

TinTower_9F_MapWarps::
	warp_def 12, 3, 3, 1, MAP_TIN_TOWER_8F
	warp_def 2, 5, 3, 2, MAP_TIN_TOWER_8F
	warp_def 12, 7, 3, 3, MAP_TIN_TOWER_8F
	warp_def 7, 9, 3, 0, MAP_TIN_TOWER_ROOF
	warp_def 16, 7, 3, 4, MAP_TIN_TOWER_7F
	warp_def 6, 13, 3, 4, MAP_TIN_TOWER_8F
	warp_def 8, 13, 3, 5, MAP_TIN_TOWER_8F

TinTower_9F_MapEvents::
	map_events TinTower_9F_EventObjects, TinTower_9F_MapWarps, 0x0, 0x0
