BattleTower_Elevator:
	.4byte BattleTower_Elevator_Layout
	.4byte BattleTower_Elevator_MapEvents
	.4byte BattleTower_Elevator_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_BATTLE_TOWER_ELEVATOR
	.byte MAPSEC_BATTLE_FRONTIER
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

