WhirlIslands_1F_NW:
	.4byte WhirlIslands_1F_NW_Layout
	.4byte WhirlIslands_1F_NW_MapEvents
	.4byte WhirlIslands_1F_NW_MapScripts
	.4byte 0x0
	.2byte MUS_DAN02
	.2byte LAYOUT_WHIRL_ISLANDS_1F_NW
	.byte MAPSEC_WHIRL_ISLANDS
	.byte 0
	.byte WEATHER_SUNNY
	.byte MAP_TYPE_UNDERGROUND
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=1, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

